### PR TITLE
Analysis terminology

### PR DESCRIPTION
**Pull request by lucernae**
### What does it fix ?
* Ticket #3726
* Funded by : DFAT

## Description

Refactor code changes caused by terminology changes

### CODE REVIEW

**Comment by lucernae** [comment]
I tried to separate it per commit, so it can be reviewed easier

**Comment by lucernae** [comment]
As discussed in the ticket. Layer title should be taken from definition

screen shot 2017-03-03 at 01 46 07

**Comment by lucernae** [comment]
Thank's I'll just merge this ASAP to avoid further conflicts

**Comment by Gustry** [comment]
Thanks a lot @lucernae

**Pull request merged**
