### PR TITLE
Docker in travis

### PR DESCRIPTION
**Pull request by Gustry**
- [x] Add notifications to .travis.yml

See #2977

### CODE REVIEW

**Comment by Gustry** [comment]
Without the dock : `Ran 512 tests in 137.505s`
With the dock : `Ran 512 tests in 865.798s`

**Comment by Gustry** [comment]
As soon as the docker image from Boundless is fixed, I will remove the qgis_testrunner.sh from this PR.

**Comment by Gustry** [comment]
@ismailsunni @timlinux This PR is ready to be reviewed. I will start to have a look why some tests are failing.

**Comment by Gustry** [comment]
Hum, I just noticed that the current travis configuration has 571 tests (PR #2962) and in this one it's only 513.

**Comment by timlinux** [comment]
@Gustry did you figure out why some tests are missing?

**Comment by Gustry** [comment]
I made a fix on develop #2988. Now it's 519 tests on develop and 513 tests in this PR. I don't know where these 6 tests are.

**Comment by Gustry** [comment]
I'm playing with vim commands between docker logs and nose logs to see the difference. I created a gist : https://gist.github.com/Gustry/09fd8a32546bc487444ce1381efa429d with my workflow at the bottom. It's not only 6 tests which are missing, docker executes more tests (not in nose) and sometimes nose has more tests (not in docker)

Vim guru, comments are welcome

**Comment by ismailsunni** [comment]
@Gustry 
Wow, it's really weird to see the diff.

I think the test that Travis doesn't start is the slow one. I haven't checked them all though. Perhaps we should just skipped the test, not mark it as slow, so we know how many test that is slow. For example : `@unittest.skip(skipped_reason)`

And from docker test, so far I can't see the pattern or reason why it doesn't run some test. First guess, perhaps the tests that related to inasafe_data, but it seems no.

**Comment by ismailsunni** [comment]
I have updated my PR to remove not slow with skipping the test in #2685 
Lets see what we are missing after this build finished

**Comment by ismailsunni** [comment]
In that build above, I got 567 tests, and 50 of them are skipped.

**Comment by Gustry** [comment]
> First guess, perhaps the tests that related to inasafe_data, but it seems no.

No, it should be fine. Travis is fetching insafe_data and the volume is mounted inside the docker container. Tests using inasafe_data were failing before, now there are ok.

Sorry for this question, should we run slow tests in travis now ?
In the new UI test window, do we need a checkbox "Include slow tests" ?
Did you find or not some slow tests in the logs when you run in QGIS UI ?

**Comment by Gustry** [comment]
Develop : https://travis-ci.org/inasafe/inasafe/builds/141318183
```
Ran 568 tests in 2320.131s
OK (SKIP=53)
```

Current status of this PR : 
```
Ran 515 tests in 685.889s
OK (skipped=40, expected failures=32)
```

**Comment by timlinux** [comment]
As per our Skype discussion - please go ahead and merge this for 3.5 with the understanding that travis docker based testing will have some expected failures. We can further refine these in 3.6 but I would not like to spend any more time working on testing framework for 3.5. LGTM

**Pull request merged**
