### PR TITLE
Fix 2969 minus number

### PR DESCRIPTION
**Pull request by ismailsunni**

### CODE REVIEW

**Comment by ismailsunni** [comment]
hi @NyakudyaA can you try my PR here for #2969 ?

**Comment by NyakudyaA** [comment]
ok @ismailsunni  will do so

**Comment by NyakudyaA** [comment]
@ismailsunni I still get the minus if I use the ash_raster and the buildings(polygons) from OSM. 
If I use the classified hazard and small_buildings I do not get an error.

minus_brancj


minus

Data: All sources from `.qgis2/python/plugins/inasafe/safe/test/data`
Hazard: `/hazard/ash_raster_wgs84.tif`
Exposure: `OSM Building polygons`

**Comment by ismailsunni** [comment]
Hi @NyakudyaA 
Thanks for the testing. I have made another commits to fix the bug, please test again.

**Comment by NyakudyaA** [comment]
@ismailsunni  LGTM

**Pull request merged**
