### PR TITLE
Reporting - action list

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix ?
* Ticket : #3960 
* Funded by : DFAT
* Description : 

qgis 2 14 12-essen - -4026_048

impact-report-output pdf_049

### CODE REVIEW

**Comment by lucernae** [comment]
@myarjunar It works in mine

Not sure why you said it doesn't work in QGIS.

screen shot 2017-04-07 at 11 21 27
screen shot 2017-04-07 at 11 21 08
screen shot 2017-04-07 at 11 21 38

**Comment by myarjunar** [comment]
thanks @lucernae , it also works on my machine now

**Comment by myarjunar** [comment]
hi @ivanbusthomi , can you check this PR for me? thanks

**Comment by ivanbusthomi** [comment]
@myarjunar - That looks great, thanks! I will check it on my machine.
a small input from @fredychandra maybe we could change the `Shelter and housing` text to just `Shelter`.

**Comment by ivanbusthomi** [comment]
Hi @myarjunar ,
I've tried the PR, in it works on my computer. Thanks!
I have a question, is it possible to separate the Action checklist into a new pdf report? So basically we remove it from the current analysis report and create a separate file called the InaSAFE action checklist.

**Comment by myarjunar** [comment]
@ivanbusthomi yes it's possible, but in #3959 charlotte said that she wanted to move it to the end. So which one will be applied? move it to the end or create a new report for action checklist?

**Comment by Gustry** [comment]
Maybe it was actions at the end when it's in the dock (because we need to display them) and in a new page to have them separated in PDF. Is it correct?

**Comment by Charlotte-Morgan** [comment]
I think a separate report is best as the list is getting very long. Every ouput (map, report tables, action list) should have some header info that says what the analysis was. 
in #3959 I comment that there is a separate ticket for action check list

**Comment by ismailsunni** [comment]
Any update for this one @myarjunar ?

**Comment by timlinux** [comment]
@myarjunar lets get this updated and merged. Can you put the actions and checklist into a separate PDF product as @Charlotte-Morgan requests?

**Comment by ivanbusthomi** [comment]
Hi mas @myarjunar - I've tried this PR again, and it looks great, thanks! I like the section that you implemented for the notes based on issue https://github.com/inasafe/inasafe/issues/4138
Could you please kindly explain why do you also separate the notes and assumptions?

**Comment by myarjunar** [comment]
@ivanbusthomi I have bring the notes back to the table report :smiley:

**Comment by timlinux** [comment]
@ivanbusthomi I asked him to make it a separate PDF document based on @Charlotte-Morgan 's comments above:

> I think a separate report is best as the list is getting very long. Every ouput (map, report tables, action list) should have some header info that says what the analysis was.
> in #3959 I comment that there is a separate ticket for action check list

**Pull request merged**
