### PR TITLE
fix #2849 building report, fix align right/left

### LINKED ISSUE #2849: Report style for buildings
## Problem

Text is right aligned in impact reports where new structure mappings are used.

## Proposed solution
All text should be left aligned
All numbers should be right aligned

make it happy

### PR DESCRIPTION
**Pull request by Gustry**
@Charlotte-Morgan I fixed the text alignment for the breakdown and for the postprocessing, like `closed buildings`.

### CODE REVIEW

**Comment by ismailsunni** [comment]
The code is LGTM. But, it looks strange. I can't decide it quickly, whether the column 0, 4, 7, 11 belongs to Medium hazard zone or High hazard zone.

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry  - based on your screenie above - I think we need to fix it some more.

I think the standard should be:
Alignment: numbers and number headings are right aligned, words and word headings are left aligned

So this means that:
Building type heading and content are left aligned
all the hazard zone headings and counts are right aligned.

Please look at all the good reports that are out there that do not need fixing and copy from them - you must have some standard code for reports that has all the basics in it. Tim did so much work on tidying up reports for 3.2

**Comment by Gustry** [comment]
Thanks for the review @Charlotte-Morgan .
Sorry if I misunderstood. I was happy to update, because I was not convinced by my PR yesterday. As Ismail said, it was not very easy to read.
This is new status :

**Comment by Charlotte-Morgan** [comment]
@Gustry - looking great thank you.
In some reports we have wrapped column headings too but I'm happy to wait for @easmetz  to get her head around some standards for these things.

**Pull request merged**
