### PR TITLE
Set transparent for raster value = 0. Per #2529.

### LINKED ISSUE #2529: Flood IF Analysis Layer Result did not Match with Hazard and Exposure Data [bug]
# Problem
Flood IF Analysis Layer Result did not Match with Hazard and Exposure Data

# Detail 
I try to run flood IF using flood Jakarta (vector) and Java Population (raster). The result generally shows good result but when I zoom in to certain area some layer is missing. There is a hole between flood layer and the result layer. It should be at least be classified in analysis layer and overlap with the flood layer but unfortunately it is empty.

# ScreenShoot
output layer flood_population2

output layer flood_population

# Platform
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.4 Wien
InaSAFE 3.2.5 dev-master

# Data
Hazard : Jakarta_Flood_18113__WGS84.shp (Vector)

Exposure : 
*Java_Population_WGS84.tiff (Raster)

Agregation : Jakarta_District_Boundary.shp	

Cc : @timlinux @ismailsunni @samnawi

### PR DESCRIPTION
**Pull request by ismailsunni**
Fix #2529. It will replace my PR in #2567

### CODE REVIEW

**Comment by samnawi** [comment]
As the proposed from @Charlotte-Morgan in the issue #2529 
image

I still find the cell with a value greater than 0 symbolized by the transparent color.
image

**Comment by timlinux** [comment]
LGTM

**Comment by ismailsunni** [comment]
Hi @samnawi 
Ah, yes. I accidentally revert my changes. I have updated it again. Please check :)

**Comment by samnawi** [comment]
@ismailsunni this is the result 
**Still in Develop Branch**
image

**When I tried your PR**
image

As the proposed from @Charlotte-Morgan, the first point is LGTM.
But for 2nd point, the 0 value should presented by transparent.

Then, I try to change the properties
image

The map will show like this 
image

**Comment by Charlotte-Morgan** [comment]
I agree with @samnawi - great explanation thank you!

**Comment by ismailsunni** [comment]
Hi @samnawi @Charlotte-Morgan 
Yes, that's what I did. My code works in qgis python script https://github.com/ismailsunni/scripts/blob/master/qgis_raster_transparency.py
but apparently, it doesn't work when I put it in InaSAFE. Need to find out. Thanks for the feedback :)

**Comment by ismailsunni** [comment]
Hmm, now I understand, the transparent is indeed not working in InaSAFE.

**Comment by samnawi** [comment]
@ismailsunni The transparent that you mean cannot work in InaSAFE is just for value = 0 ?
Because in the current, The transparent can work for 0 - 1 cell value.
selection_066

**Comment by ismailsunni** [comment]
Did you set the transparency from layer properties or doing nothing (from InaSAFE) ?

**Comment by samnawi** [comment]
The picture in above is properties come from InaSAFE result

**Comment by ismailsunni** [comment]
Update,
After some discussion (and confusion) with @samnawi, we found that there is a problem in InaSAFE in OSX. In OSX, the transparency set doesn't work properly. But it works on Windows and Ubuntu.

I will make it work in Ubuntu first, then try to fix it on OSX.

**Comment by ismailsunni** [comment]
Result comparison Ubuntu vs OSX (ignore the number, since it's different analysis extent ):

1. OSX (Not transparent)
osx


1. Ubuntu 14.04 (Transparent)
ubuntu-14 04

Both are using develop, and the same scenario


@lucernae @timlinux can you try the scenario also in OSX? to make sure, it's not me.

**Comment by samnawi** [comment]
For Transparent issue :+1: 
LGTM in my Ubuntu and Windows machine.

**Pull request merged**
