### PR TITLE
Revert "be sure that we have a Message instance"

### PR DESCRIPTION
**Pull request by ismailsunni**
This reverts commit ae2bead30c4ae2d01bec358d31a28e9896189b93.

### What does it fix?
* Ticket: No ticket
* Funded by: DFAT
* Description: 
  - Sorry @Gustry , I can't run analysis properly with that commit. After reverting, I can run it normally.

### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [x] Request someone to review or test your PR

### CODE REVIEW

**Comment by ivanbusthomi** [comment]
Hi @ismailsunni - I've tested it and the error has gone.

**Comment by samnawi** [comment]
:+1:

**Comment by Gustry** [comment]
Sorry for that!
Why not fixing instead of reverting? It was 2 lines to fix.

**Comment by ismailsunni** [comment]
@Gustry sorry, I was wired to my debugging and needs quick solution. I thought it was difficult. Turns out, only 2 lines :D 

Thanks

**Pull request merged**
