### PR TITLE
Class count

### PR DESCRIPTION
**Pull request by Gustry**
This PR is based on the other PR #2564 .
It removes everything about statistics.

### CODE REVIEW

**Comment by ismailsunni** [comment]
LGTM, thanks for removing it from metadata also.

**Comment by lucernae** [comment]
Is it just me, or Travis check is missing from this PR?

**Comment by Gustry** [comment]
@lucernae Yes, Travis is missing on this PR. It happens many time for 2 weeks for me. Am I the only one ? Sometimes if I put more commits, it will be ok, but this PR is finished

**Comment by ismailsunni** [comment]
@Gustry I never see this problem before. Anyway, perhaps we need to update our travis configuration. See : #2150

**Comment by Gustry** [comment]
ok, Travis is coming back

**Pull request merged**
