### PR TITLE
Paper cut

### PR DESCRIPTION
**Pull request by ismailsunni**
- Move InaSAFE keyword version comparison to definitions.py
- Unique volcano names
- PEP8rfectionist :D 

Please test @ivanbusthomi or @felix-yew especially the second item.
And @timlinux for the first item.

### CODE REVIEW

**Comment by Gustry** [comment]
LGTM

**Comment by ismailsunni** [comment]
hi @Gustry 
I got this on travis:
```
90.15s$ docker pull elpaso/qgis-testing-environment:${QGIS_VERSION_TAG}
release-2_14: Pulling from elpaso/qgis-testing-environment
ent
Tag release-2_14 not found in repository docker.io/elpaso/qgis-testing-environment
```

Any idea?

**Comment by ismailsunni** [comment]
A reply for my question above, just restart the test in travis.

**Comment by felix-yew** [comment]
Hi mas @ismailsunni 

I have tried your PR, and I think the repetition did not appear again. But, there is another problem appear.

In the 'Total population in the analysis area: 132000', maybe we can give a thousand separator to make an easy read the number.

And then, in the another point:
image
What the 'Volcanoes considered' mean in the Notes and assumptions?

Make it happy :smile:

**Comment by felix-yew** [comment]
Hi mas @ismailsunni 

Sorry, I forgot something about the report table. In the 'Analysis Result', the radius of a volcano is not a sequence.
image

Maybe we can make it to sequence radius from high radius to low radius. For this example: from radius 10 km, 5 km, to 3 km.

Make it happy :smile:

**Comment by felix-yew** [comment]
Hi mas @ismailsunni 

About the repetition name of Ebulobo, there are something interesting about population data. When I use population data from **AsiaPop**, the result becomes like this :
image
This problem like similar like in InaSAFE 3.4. We hope it can be fixed before InaSAFE 3.5 release.

Make it happy :smile:

**Comment by ismailsunni** [comment]
hi @felix-yew
I have addressed the issues that you mentioned in the comment in my commit above. Can you try it?

**Comment by felix-yew** [comment]
Ok mas @ismailsunni 

After try it, I will share the result.

**Comment by felix-yew** [comment]
Hi mas @ismailsunni 

I have tried the PR and the repetition has been fixed :+1: 
image

But, the thousand separator not repair?
image

**Comment by felix-yew** [comment]
Yeah, LGTM

image


:+1:

**Pull request merged**
