### PR TITLE
Report and Infographic Sawcut

### PR DESCRIPTION
**Pull request by lucernae**

### CODE REVIEW

**Comment by lucernae** [comment]
issue #3693 : Adjustments for map template
- Change with new qpt template
- Change supporters logo
- Change Software Version text to Software
- Change Spatial Reference text to Reference

**Comment by timlinux** [comment]
This is looking good @lucernae ! +1 from me to merge

**Comment by lucernae** [comment]
Thank's! Not final though. More commits coming.

**Comment by Gustry** [comment]
Looks good to me, thanks !

**Pull request merged**
