### PR TITLE
Refactoring Post Processor to Avoid Circular Import

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: #4482 
* Funded by: DFAT
* Description: 
   - Since I found circular import when using get_displacement_rate from the profile, I need to do refactoring of it. It's still on progress though.

### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
This looks dangerous. Good luck!

**Comment by ismailsunni** [comment]
@Gustry yes, it does.

**Comment by Gustry** [comment]
No way you can avoid to change these imports?

Please before merging, can you add the list of files to `scripts/checkout_back_after_cleaning_from_pycharm.sh ` ? I plan to run this script from month to month. Now, you understand why I added this file ;-)

 Add a comment too about your files.

Thanks

**Comment by ismailsunni** [comment]
> No way you can avoid to change these imports?

AFAIK, no. Since I the post_processor needs to import from settings, and settings need to import from definitions. So, I need to pull out this module from definitions (like I did in this PR).

> Please before merging, can you add the list of files to scripts/checkout_back_after_cleaning_from_pycharm.sh ? I plan to run this script from month to month. Now, you understand why I added this file ;-)

which list of files? I think the pattern in that script is enough.

**Comment by Gustry** [comment]
Euh, no, all your files `safe/gis/vector/prepare_vector_layer.py`, `safe/gis/vector/recompute_counts.py` etc ...

**Comment by ismailsunni** [comment]
> Euh, no, all your files safe/gis/vector/prepare_vector_layer.py, safe/gis/vector/recompute_counts.py etc ...

It seems I still do not understand about it. Can you elaborate it @Gustry ?


Btw, it's green again now. :D

**Comment by Gustry** [comment]
> It seems I still do not understand about it. Can you elaborate it @Gustry ?

Next time I will run the "optimize imports", it will erase all your work of reordering imports. Then I run the script 'checkout_back_after_cleaning_from_pycharm.sh' to rollback pycharm's changes. So you need to add all files that you don't want to be updated by PyCharm.

LGTM for the code ;-)
Sorry for the iface, I will try again, I know which test to check now.

**Comment by ismailsunni** [comment]
> Next time I will run the "optimize imports", it will erase all your work of reordering imports. Then I run the script 'checkout_back_after_cleaning_from_pycharm.sh' to rollback pycharm's changes. So you need to add all files that you don't want to be updated by PyCharm.

Ah I see. I think it's fine to not put these files in the script. The circular import is not caused by the import ordering, but more on the directory structure, that's why I move the post processor from the definitions.

**Pull request merged**
