### PR TITLE
Reporting column order

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix ?
* Ticket : #3964 
* Funded by : DFAT
* Description : 

selection_073

selection_074

### CODE REVIEW

**Comment by myarjunar** [comment]
@ivanbusthomi would be great if you could try this PR first because I'm not quite sure if it works with another data that I haven't tried of :+1:

**Comment by ivanbusthomi** [comment]
Ok mas @myarjunar , I will check this PR real quick

**Comment by ivanbusthomi** [comment]
@myarjunar LGTM :+1:

**Comment by timlinux** [comment]
@myarjunar why the Vii in the title header?

screen shot 2017-05-11 at 4 00 27 pm

**Comment by myarjunar** [comment]
> @myarjunar why the Vii in the title header?

@timlinux because Vii is the hazard class name. cmiiw

**Comment by ismailsunni** [comment]
@timlinux @myarjunar I think it's from VII (roman number for 7). We should not change the case :D

**Comment by myarjunar** [comment]
selection_075

@timlinux @ismailsunni yap it's better like this, thanks

**Pull request merged**
