### PR TITLE
add displacement ratio to the attribute table

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix ?
* Funded by : DFAT
* Description : add displacement ratio to the attribute table

screen shot 2017-02-27 at 14 40 18

### CODE REVIEW

**Comment by timlinux** [comment]
I think this is one case where showing 3 decimal places would be good.

**Comment by timlinux** [comment]
I wonder also if it would be more explicit to call the column "population_displacement_rate" so that in the future we can allow for e.g. "aged_displacement_rate" and other such vulnerability indicators....

**Comment by Gustry** [comment]
> I think this is one case where showing 3 decimal places would be good.

It's showing only 0 or 1 because the displacement ratio is only 0 and 1 ;-) The field is already with 3 digits precision and it's working fine with a displacement ratio different than 0 and 1.

> I wonder also if it would be more explicit to call the column "population_displacement_rate"

Ok, I'm going to rename it.

**Comment by Gustry** [comment]
> I wonder also if it would be more explicit to call the column "population_displacement_rate"

Ok done, I put : `population_displacement_ratio`, we said rate is for banking ;-) Is-it ok like this ?

**Pull request merged**
