### PR TITLE
fix issue #3877: Add displacement rates description in the notes

### PR DESCRIPTION
**Pull request by lucernae**
### What does it fix ?
* Ticket #3877
* Funded by : DFAT
* Description : Add generic template of displacement rates description in the notes

### CODE REVIEW

**Comment by lucernae** [comment]
Screenshot: 

screen shot 2017-02-21 at 02 20 04

**Comment by ismailsunni** [comment]
LGTM

**Comment by timlinux** [comment]
@lucernae I merged for you... thanks!

**Comment by lucernae** [comment]
Yup, thanks!

**Pull request merged**
