### PR TITLE
Update to Wizard text 

### LINKED ISSUE #2674: We need to review wizard text
Hi @easmetz 
I would like you to review all the wizard text to ensure that descriptions are clear and unique and that the user is guided well from one step to the next.

### PR DESCRIPTION
**Pull request by easmetz**
### Problem

Wizard text being reviewed (in progress

fix #2674

### Solution
Changed some grammar, wording and "\n" to "<p>" (I assumed that the intention of \n was to create a new line)

### CC

@timlinux
@Charlotte-Morgan

### CODE REVIEW

**Comment by ismailsunni** [comment]
Hi @easmetz 
Thanks for the PR. I was wondering whether it's better to use `\n` or `<p>` tag. The intention is indeed for new line. But I am not sure all renderer will "accept" <p> tag.
Let's ask @timlinux for his long experience.

**Comment by timlinux** [comment]
@ismailsunni  @easmetz yes \n is for newlines. Its ok to change them to ``<p>`` (or even better a ```<br/>``` tag since it does not need closure) if you need to make other changes to the paragraph, but please avoid changing them just for form's sake as the changes will create work for translators. Thanks!

**Comment by easmetz** [comment]
No worries, I changed it because it wasn't creating a new line, just keeping it all as one big paragraph in my Windows environment.

**Comment by ismailsunni** [comment]
Hi @easmetz 
Can you update it with develop. There is new PR merged in the develop, and make a new conflict in this PR. Thanks :)

**Comment by Gustry** [comment]
Everything is fine on this PR now ;-)

**Pull request merged**
