### PR TITLE
Add initial infographic support for minimum needs and population

### PR DESCRIPTION
**Pull request by lucernae**
Mainly for issue #3473 

- Add pie chart support generator
- Add infographic report

### CODE REVIEW

**Comment by lucernae** [comment]
Generated Sample
screen shot 2017-01-11 at 16 38 41

**Comment by Gustry** [comment]
Just looking at the screenshot, it looks a very good start !

**Comment by lucernae** [comment]
@timlinux wants the blue one.
screen shot 2017-01-11 at 18 15 06

I don't know why somehow svg's were not displayed in the dock.

screen shot 2017-01-11 at 18 15 50

But this svg is able to be displayed...

screen shot 2017-01-11 at 18 15 37

And if you right click > Open in web browser, you can see it?

**Comment by felix-yew** [comment]
:+1: 
This is a good start mas @lucernae

**Comment by felix-yew** [comment]
I just wanna give an example if we use the template in blue format.

blue

Mas @lucernae about the chart, maybe better if we can move it below the chart to fit the size.

**Comment by lucernae** [comment]
Thank you, Felix!

**Comment by lucernae** [comment]
I will continue infographic in the next PR.
Merge this for the refactor and map report

**Pull request merged**
