### PR TITLE
WIP - Tsunami raster building IF

### PR DESCRIPTION
**Pull request by ismailsunni**

### CODE REVIEW

**Comment by ismailsunni** [comment]
Hi @samnawi can you try this new IF?

**Comment by samnawi** [comment]
:+1: 

LGTM

**Comment by ismailsunni** [comment]
Update:
- Adding dry zone
- Change color

screen shot 2016-01-04 at 11 51 48 am

**Comment by samnawi** [comment]
LGTM for add dry class and update the color.
But, there is some note for it :
* Update the note also for dry class
* I found some wrong calculated in this picture

image

Some building that I pointed with the arrow is 100% position in 0 meters, but the classified in low class, not dry class.

Thank you.

**Comment by timlinux** [comment]
@samnawi wrote:

> Some building that I pointed with the arrow is 100% position in 0 meters, but the classified in low class, not dry class. Maybe it's similar with issue #2419.

I think this issue will always be present whilst we are using interpolation. As soon as we can move to direct value lookups (with building classified according to the largest cell value it touches) this issue will go away.

**Comment by ismailsunni** [comment]
@timlinux 
Yes, that's what I thought. Should I continue working on this, or wait for the interpolation removal first?

**Pull request merged**
