### PR TITLE
fix import from the parameters submodule

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?
* Ticket: #4383 
* Funded by: DFAT
* Description: Fix import

@ismailsunni ?

### CODE REVIEW

**Comment by ismailsunni** [comment]
Looks good.

But I think I will need to check my "trick" in that file
```
# Note(IS): I need to use alias to make sure it throws the same exception class
from parameters.parameter_exceptions import (
    InvalidValidationException as OriginalValidationException)
```

Let's wait for @felix-yew or @samnawi to check the PR

**Comment by samnawi** [comment]
LGTM

**Comment by felix-yew** [comment]
The KW's dialog box appear, but when I try to set the aggregation I got this message

```
Traceback (most recent call last):
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\wizard_dialog.py", line 678, in on_pbnNext_released
    new_step.set_widgets()
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_kw44_fields_mapping.py", line 114, in set_widgets
    self.parent.layer, on_the_fly_metadata)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\field_mapping_widget.py", line 58, in set_layer
    self.populate_tabs()
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\field_mapping_widget.py", line 79, in populate_tabs
    tab.set_layer(self.layer, self.metadata)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\field_mapping_tab.py", line 152, in set_layer
    self.populate_parameter()
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\field_mapping_tab.py", line 264, in populate_parameter
    vertical=False
TypeError: __init__() got an unexpected keyword argument 'vertical'
```

And the set KW for aggregation stop in Name section.

**Comment by Gustry** [comment]
@ismailsunni is doing another patch for this one

**Pull request closed without merging**
