### PR TITLE
Fix 4151 add help text field group

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix ?
* Ticket : #4151 
* Funded by : DFAT
* Description : 
  - Adding help text for field in field mapping
screen shot 2017-05-12 at 13 08 02

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - this looks good to me.
image
It is not yet picking up the new default ratios, even though PF #4144 is merged?

**Comment by ismailsunni** [comment]
@Charlotte-Morgan 
the screenshot is created before #4144 merged. But it will use the new default ratios if we merged. Magic.

**Comment by myarjunar** [comment]
LGTM

**Comment by timlinux** [comment]
Thanks very much @ismailsunni

**Pull request merged**
