### PR TITLE
add pt locale

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix?

* Ticket: #
* Funded by: 
* Description: 
  * 

### Checklist:

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
Missing the change in the Makefile IIRMC

**Comment by myarjunar** [comment]
Hi @Gustry , it's nice to hear from you again!
I have added pt to the list of `LOCALES`. hmm so that's why I cannot see the translated pt string in the desktop? It works on unittest tho, meaning it will also work on headless. Thanks!

**Comment by ismailsunni** [comment]
@myarjunar 
please add the new language in this make command also `test-translations`

**Comment by ismailsunni** [comment]
For the not running analysis, perhaps we should add `inasafe_4` branch to the `.travis.yml` file

**Pull request merged**
