### PR TITLE
update population place exposure report with exposed population

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix?
* Ticket: #4783 
* Funded by: DFAT
* Description: 
selection_167

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by ismailsunni** [comment]
Can you give sample result @myarjunar ?

Mas @samnawi , perhaps you want to check this.

**Comment by samnawi** [comment]
image

hi @myarjunar and @ismailsunni Seem like the number of total exposed population which I got is the sum of exposed + not exposed.
Have you checked the analysis using the data that will generate not exposed impact?

**Comment by myarjunar** [comment]
Hi @samnawi thanks for the report, I took the total pop because there is still no total exposed pop in the analysis summary, it will be correct once @ismailsunni added exposed pop to the analysis_summary

**Comment by samnawi** [comment]
Ok @myarjunar I guess it's like in pivot table where you can summarize all of the population which have exposed class :smiley:

**Comment by ismailsunni** [comment]
Hi @myarjunar and @samnawi I will merge this one first, so that I can make a PR to this change in develop.

**Pull request merged**
