### PR TITLE
Fix #2798 Attribute Error

### LINKED ISSUE #2798: Attribute error on analysis using training dataset
### Problem
Running analysis using the `Run intermediate Inasafe training` results in attribute error when aggregation is done by district  `Jakarta`.

Dataset used: [http://data.inasafe.org/TrainingDataPackages/Run%20Basic%20InaSAFE%20v3.2.zip]()

Run Intermediate InaSAFE/DKI Jakarta/01 Hazard Data/Jakarta_Flood_18113_WGS84.shp
```
This analysis will calculate the impact of A Flood in Jakarta like 2013 on People and bullet list the results aggregated by Jakarta District
Problem

The following problem(s) were encountered whilst running the analysis.

AttributeError

An exception occurred when running the impact analysis.
'NoneType' object has no attribute 'difference'
Diagnostics

In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 678, in run_analysis self._prepare()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 833, in _prepare self.aggregator.deintersect()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 476, in deintersect self.hazard_layer)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 1443, in _prepare_polygon_layer int_com.difference(int_sym))
```

### Expected Behaviour
Run without errors and produce analysis result

### Environment
Linux QGIS 2.14.2

### Proposed Solution

### PR DESCRIPTION
**Pull request by ismailsunni**
By pass if there is None geometry for #2798 

Please check @timlinux @Charlotte-Morgan @Gustry

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks @ismailsunni. It's a solution, but I'm wondering why we got this unknown geometry and not before (ie a few months before).

**Comment by ismailsunni** [comment]
@Gustry well, I am wondering that also actually. No idea though.

**Comment by timlinux** [comment]
I haven't looked deeply into it but it may be a side effect of the new geometry classes in QGIS....though those were added a while ago....

**Comment by ismailsunni** [comment]
@timlinux so, is it ok for me to merge it?

**Comment by timlinux** [comment]
yes LGTM thanks

**Pull request merged**
