### PR TITLE
Earthquake fix

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix ?
* Ticket #3803 
* Description : @ivanbusthomi Can you check this PR for this issue ? thanks

### CODE REVIEW

**Comment by ivanbusthomi** [comment]
Hi @Gustry , using aggregation I got an error
```
The following problem(s) were encountered whilst running the analysis.
Exception

Diagnostics
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1017, in run self._run()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1160, in _run self.aggregation_preparation()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1410, in aggregation_preparation raise Exception
```

Without aggregation, I got something like this in the dock with the busy cursor. No number of people affected.
image
 I used `West Sumatara` dataset

**Comment by Gustry** [comment]
For number 2, you should have something in inasafe logs.

**Comment by ivanbusthomi** [comment]
HI @Gustry I tried updating my aggregation keyword, and received another error. I tried it both using aggregation and without aggregation.

```
The following problem(s) were encountered whilst running the analysis.
KeyError

Details
These additional details were reported when the problem occurred.
1

Diagnostics
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1017, in run self._run()
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1171, in _run self.damage_curve_analysis()
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1273, in damage_curve_analysis self.earthquake_raster_population_raster()
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1316, in earthquake_raster_population_raster exposed, self.aggregation, earthquake_function())
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/ivanbusthomi/.qgis2/python/plugins\inasafe\safe\impact_function\earthquake.py", line 361, in make_summary_layer for mmi, mmi_exposed in exposed_per_agg_zone[agg_zone].iteritems():
```

**Comment by Gustry** [comment]
I will manage this PR in #3734

**Pull request closed without merging**
