### PR TITLE
add styles to flood test data and fix data audit for census

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by timlinux** [comment]
Can you include a screenie of the rendered styles for those looking at this PR?

Thanks

**Comment by Gustry** [comment]
Sorry, I forgot that you want the flood prone in blue. I've fixed that.

This is only a QML for test layers so the aim of this PR is only for us. But maybe we should define some common colors : flood prone YES/NO ...

style

**Comment by timlinux** [comment]
Thanks that looks good @Gustry - perhaps put it to 50% transparency too?

**Comment by Gustry** [comment]
I will merge. I have already set transparency to 30%.

**Pull request merged**
