### PR TITLE
replace QtWebkitWidgets/QWebView to PyQt4.QtWebKit

### PR DESCRIPTION
**Pull request by mbernasocchi**
shouldent this be like this?
I keep on getting error if I dint change

### CODE REVIEW

**Comment by mbernasocchi** [comment]
Hi @timlinux I ve no idea how can QtWebkitWidgets/QWebView be working for you guys. Same thing for the resource sharing plugin.

This happens when in designer you promote a qwidget

**Comment by mbernasocchi** [comment]
Also using 2.14 I get the same.

```
Couldn't load plugin inasafe-dev due to an error when calling its initGui() method 

ImportError: No module named QtWebKitWidgets.QWebView 
Traceback (most recent call last):
  File "/usr/local/qgis/214/share/qgis/python/qgis/utils.py", line 315, in startPlugin
    plugins[packageName].initGui()
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/plugin.py", line 547, in initGui
    self._create_dock()
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/plugin.py", line 523, in _create_dock
    from safe.gui.widgets.dock import Dock
  File "/usr/local/qgis/214/share/qgis/python/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 114, in 
    from safe.gui.tools.help_dialog import HelpDialog
  File "/usr/local/qgis/214/share/qgis/python/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/gui/tools/help_dialog.py", line 30, in 
    FORM_CLASS = get_ui_class('help_dialog_base.ui')
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/utilities/resources.py", line 100, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 41, in 
  File "/usr/local/qgis/214/share/qgis/python/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named QtWebKitWidgets.QWebView


Python version: 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914] 
QGIS version: 2.14.9-Essen Essen, 912a7eb 

Python Path:
/usr/local/qgis/214/share/qgis/python
/home/marco/.qgis2/python
/home/marco/.qgis2/python/plugins
/usr/local/qgis/214/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/marco/.local/lib/python2.7/site-packages
/opt/pycharm-2016.2.3/debug-eggs/pycharm-debug.egg
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
/home/marco/.qgis2//python
/home/marco/.qgis2/python/plugins
/home/marco/.qgis2/python/plugins/inasafe-dev
/home/marco/.qgis2/python/plugins/inasafe-dev/safe_extras/parameters
/home/marco/.qgis2/python/plugins
/home/marco/.qgis2/python/plugins/inasafe-dev/safe_extras
```

**Comment by Gustry** [comment]
It's still working on my mac with this fix. It looks OK to me. Can we squash to develop ?

**Comment by ismailsunni** [comment]
I can't see any difference in my QGIS 2.14 OSX. Does it fix issue on QGIS 2.18?

**Comment by timlinux** [comment]
LGTM please merge when ready

**Comment by Gustry** [comment]
@mbernasocchi @timlinux I'm gonna merge this one for the beta release tomorrow.

**Pull request merged**
