### PR TITLE
In progress refactoring of postprocessors for #2370

### PR DESCRIPTION
**Pull request by timlinux**
**Note this PR is not ready for merge yet**

This PR seeks to address #2370 and other related issues. I am removing hard coded category lists from the post processors. I think ultimately I will be moving all the aggregation logic into the impact functions.

### CODE REVIEW

**Comment by samnawi** [comment]
I've got the error message when run it, use the data like @fredychandra use in #2370 
selection_203

**Comment by Gustry** [comment]
I think PR https://github.com/inasafe/inasafe/pull/2743 is going to replace this one.
Can we close this one @timlinux ? Now, we have the `value_mapping` keyword.

**Comment by timlinux** [comment]
I am closing this as we have gone down a different route with value map

**Comment by timlinux** [comment]
I am closing this as we have gone down a different route with value map

**Pull request closed without merging**
