### PR TITLE
CM test workflow

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
### What does it fix ?
* Ticket : #
* Funded by : 
* Description : 
nothing is fixed
this PR is to test new laptop software installs and git workflow before doing too much

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
yay

**Comment by ismailsunni** [comment]
LGTM @Charlotte-Morgan :)

**Comment by Charlotte-Morgan** [comment]
I think we should not merge this @ismailsunni

**Comment by ismailsunni** [comment]
Haha, yes +100 to not merge :D

**Comment by Charlotte-Morgan** [comment]
closing this with no merge

**Pull request closed without merging**
