### PR TITLE
Profile memory

### PR DESCRIPTION
**Pull request by timlinux**
### What does it fix ?

* Ticket : #4106 
* Funded by : DFAT
* Description : Adds support for memory profiling to InaSAFE

Will help use find where we are leaking / using a lot of memory.

Still a work in progress

### CODE REVIEW

**Comment by Gustry** [comment]
Nice !
I'm wondering why you have the metadata file again in this PR.

**Comment by timlinux** [comment]
@Gustry its a mistake - should be gone in my next push

**Comment by timlinux** [comment]
qgis

**Comment by timlinux** [comment]
@ismailsunni can you review please?

**Pull request merged**
