### PR TITLE
remove empty lines from postprocessing outputs #2318

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - I tested this with BIG (non OSM) infrastructure data and  Ambon tsunami raster aggregated by district.
The If ran but the results are not what I expect.
I got 3 impact layers: one affected and two of the village boundary with counts of affected infrastructure.
The impact report did not have an aggregation report.
Is it possible you have made an aggregation map not an aggregation report?
[2904.pdf](https://github.com/inasafe/inasafe/files/299317/2904.pdf)
[2904_table.pdf](https://github.com/inasafe/inasafe/files/299318/2904_table.pdf)

**Comment by Gustry** [comment]
I have some data on Ambon, but I can't replicate your issue with a tsunami in Ambon aggregated by `Ambon Malteng`.
Can you tell me exactly which dataset you used or can you share it to me ? Thanks.

For information, Christian added a function to remove empty columns. I added a function to remove empty lines (containing exclusively 0 and "No data").

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry - LGTM with a minor edit to this statement _"Columns or lines containing exclusively ) and "no data" have not been shown in the table"_

Please: 

- remove this statement from the table footer and place it in the notes and assumptions for the entire report.
- change the text to say _"columns and rows containing only 0 or 'no data' values are excluded from the tables"_
- add this new note item as a standard to #2920

**Comment by Gustry** [comment]
Ok, I'm going to edit this statement.
But what about your bug in Ambon ?

**Comment by Charlotte-Morgan** [comment]
Oh - i could not replicate it :)

**Comment by Gustry** [comment]
@Charlotte-Morgan I just fixed the sentence. It will still be shown in the table footer and not in the notes.
This PR is going to be easy to backport to master for 3.4.1.

To change the notes, I need a deeper change, so I prefer to do it in another PR to not mix to much things in one PR. Sorry for that. I'm going to merge this one.

**Comment by Charlotte-Morgan** [comment]
Perfect. 
Great choice. 

Charlotte  Morgan

**Pull request merged**
