### PR TITLE
Partfix #2272

### PR DESCRIPTION
**Pull request by easmetz**
Inserted definitions of **displaced** and **evacuated** into population in buildings/population notes (as they are the same). I am not completely sure if I have cited correctly as the link is too long for the space available. The definitions are slightly inconsistent in their wording as I have used the exact UNISDR definitions. I think it would be wise to edit them for consistency of wording (ie persons vs people, etc) but I'm open to comment.

The notes and assumptions now look like this:
image

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz a couple of comments from me but maybe @timlinux can advise.

- I think its ok to leave a hyper link longer than the 80 characters ie no need to wrap it.
- I think the word people is better in this case than persons
- The notes for displaced should only be added to impact functions that mention displaced people
- The notes for evacuated should only be added to impact functions that mention evacuated people

this links back to #2920 regarding when we should use the words evacuated and displaced. Now we have definitions we can make some recommendations in the standard

not sure why the test has failed

**Comment by easmetz** [comment]
I have now changed "persons" to "people" in line with your comments @Charlotte-Morgan

**Comment by timlinux** [comment]
hi @easmetz and @Charlotte-Morgan 

Hi @easmetz a couple of comments from me but maybe @timlinux can advise.

> I think its ok to leave a hyper link longer than the 80 characters ie no need to wrap it.

Yes for Markdown, no need to adhere to 80 chars for links. For readability and version difference visualisation it is still generally a good idea to put line breaks in at around 80 chars where possible.

> I think the word people is better in this case than persons

+1

> The notes for displaced should only be added to impact functions that mention displaced people

+1

> The notes for evacuated should only be added to impact functions that mention evacuated people

+1 

> this links back to #2920 regarding when we should use the words evacuated and displaced. Now we have definitions we can make some recommendations in the standard

> not sure why the test has failed

That are all passing now it seems...

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz this is taking shape nicely.  
A few more suggestions from me that maybe @timlinux can confirm or dismiss.
- [ ] This document is the 'standard' not the RFC which was the proposal. I would encourage you to use 'stronger' language to describe the standard. ie Instead of **we propose the title** ... we could write **The title should have the following syntax**
- [ ] I would prefer that this document should have paragraphs and sentences with pictures, tables and dot point lists. It should avoid being a list of notes, we already have that in the RFC.

**Comment by timlinux** [comment]
Hi @easmetz and @Charlotte-Morgan 

> This document is the 'standard' not the RFC which was the proposal. I would encourage you to use 'stronger' language to describe the standard. ie Instead of we propose the title ... we could write The title should have the following syntax

Agreed

> I would prefer that this document should have paragraphs and sentences with pictures, tables and dot point lists. It should avoid being a list of notes, we already have that in the RFC.

Agreed - as a minimum, a stranger coming to the project should be able to make sense of the reporting standards without needing a lot of *a priori* knowledge of the project.

**Comment by easmetz** [comment]
I have separated these two out into two separate pull requests:

definitions.py changes = #3077
reporting standards changes = #3078

**Pull request closed without merging**
