### PR TITLE
mistakes in wizard dialog

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by ismailsunni** [comment]
LGTM

**Comment by ismailsunni** [comment]
LGTM again :)

**Comment by Gustry** [comment]
Thanks Ismail for your hard work for reviewing !
I will keep this PR open,  I have some other mistakes to fix :)

**Comment by Gustry** [comment]
@ismailsunni I'm going to merge this PR.
Can you push to transifex asap so as to update strings ? Thanks.
We need to backport this PR and translations to master. Should I open a PR against master ?

**Comment by ismailsunni** [comment]
@Gustry ok, I have pushed the strings to transifex.
Yes, you should make the same PR against master

**Pull request merged**
