### PR TITLE
Remove too complex provenance from project variable. Fix #4436

### LINKED ISSUE #4436: Store Complicated Dictionary as HTML String in Project Variable
### Problem
Currently we store complicated dictionary like action list or notes as as normal string with generated key in the project variable. Example of the keys are: `dictionary_key__dictionary_key: value` or `list_key__1`, `list_key__2`. Turns out, this is not easy to be retrieved in the report.

### Proposed Solution
Change to store them as HTML String in the project variable so that it's easy to retrieved in the report.

cc @timlinux @myarjunar

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: #4436 
* Funded by: DFAT
* Description: 
   - Remove too complex provenance from project variable. Fix #4436
### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [x] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
Can we also remove duplicate? I think OS, etc

**Comment by ismailsunni** [comment]
@Gustry Done. Currently, there is only `os` that is duplicate. We need to add some variables in the QGIS (perhaps I will do it for QGIS 3.0).

**Comment by Gustry** [comment]
Yes, it could be nice to reduce InaSAFE variables which belong to QGIS.

I don't know if the QPT is using the OS variable already.

**Comment by ismailsunni** [comment]
Thanks @Gustry 
Can you give me comment regarding @Gustry 's comment above @myarjunar ?

**Comment by ismailsunni** [comment]
I have checked with @myarjunar, OS is not used from variable, but from provenance. So, my changes are safe. Will merge this after travis says ok.

**Pull request merged**
