### PR TITLE
WIP : refactoring analysis

### PR DESCRIPTION
**Pull request by Gustry**
- [ ] safe_layer.py : docstring, implementation

### CODE REVIEW

**Comment by Gustry** [comment]
I noticed that there a few methods [show/send]_dynamic_message, static_message ... in safe. Do you think I can continue the refactoring using safe/common/signals.py as in my PR ?

CC @timlinux @lucernae @ismailsunni

**Comment by ismailsunni** [comment]
From me, I think it's ok to do it. Perhaps, we can use it in another place.

**Comment by Gustry** [comment]
Thanks @ismailsunni. Yes this code is duplicated in inasafe, I can use it in some places if I continue this small refactoring.

**Comment by timlinux** [comment]
@Gustry can you freshen your PR so it is mergable? Can you update on the status?

**Comment by Gustry** [comment]
This PR has been split into many small PR. I'm going to close this one.

**Pull request closed without merging**
