### PR TITLE
avoid renaming fields if they are used many times

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?
* Ticket: #4721 
* Funded by: DFAT
* Description: avoid renaming fields if they are used many times

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry - it seems to run and the results appear in the dock. No output layers are added to the TOC. At the same time I get a crash dump and an option to close the program ..
image

So its different now :)

**Comment by Gustry** [comment]
My PR is only rolling back to the previous code used in 4.3. So AFAIK, the crash is not related to my PR or it's also crashing if you do the test with 4.3.

It was a new code introduced in November

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry - this is a blocker for me to get my work done for partners tomorrow. Should I go back to 4.2 or manually do separate analysis for age and then vulnerability?

**Comment by Gustry** [comment]
Let me know when you wake up, I can still fix tonight if it's a blocker for you ;-)

**Comment by Gustry** [comment]
For my notes, this PR is partially reverting a new feature introduced in develop during 4.3 development: https://github.com/inasafe/inasafe/pull/4694 ticket #3434

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry - thankyou this is  working well for me now.

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry  - I have more of the same problem.
I was able to run the analysis where I used total population as females and then specific fields for age, gender and vulnerability - reusing fields - ie infants.

Now I want to run the analysis for males but I am getting an error about females. I am using the same data, only changing the key words.
here are my key words
image

Error message in the dock
image

Log message
```
2017-12-06T13:46:04	0	Sentry logging enabled in safe
2017-12-06T13:47:49	0	ANALYSIS : The impact function is starting.
2017-12-06T13:47:49	0	Datastore : C:/20171204 UNOCHA Update/3_Results/EarthquakeRasterOnPopulationPolygon_06December2017_13h47-49.893000
2017-12-06T13:47:49	0	ANALYSIS : Pre processing
2017-12-06T13:47:49	0	ANALYSIS : Aggregation preparation
2017-12-06T13:47:49	0	aggregation: provided: True
2017-12-06T13:47:49	0	impact function: crs: EPSG:4326
2017-12-06T13:47:49	0	aggregation: Cleaning the aggregation layer
2017-12-06T13:47:50	0	Features which have been removed from aggregation : 0
2017-12-06T13:47:50	0	We add an ID column in aggregation
2017-12-06T13:47:50	0	Fields which have been removed from aggregation : ID District Subdistric Village Label
2017-12-06T13:47:50	0	infant_ratio_field is not in the detected in the aggregation layer AND infant_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	child_ratio_field is not in the detected in the aggregation layer AND child_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	youth_ratio_field is neither a constant nor a field in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will do nothing about it.
2017-12-06T13:47:50	0	adult_ratio_field is neither a constant nor a field in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will do nothing about it.
2017-12-06T13:47:50	0	elderly_ratio_field is not in the detected in the aggregation layer AND elderly_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	male_ratio_field is not in the detected in the aggregation layer AND male_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	female_ratio_field is not in the detected in the aggregation layer AND female_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	under_5_ratio_field is not in the detected in the aggregation layer AND under_5_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	over_60_ratio_field is not in the detected in the aggregation layer AND over_60_count_field is detected in the exposure layer. We do nothing in this step.
2017-12-06T13:47:50	0	child_bearing_age_ratio_field is neither a constant nor a field in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will do nothing about it.
2017-12-06T13:47:50	0	pregnant_ratio_field is neither a constant nor a field in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will do nothing about it.
2017-12-06T13:47:50	0	lactating_ratio_field is neither a constant nor a field in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will do nothing about it.
2017-12-06T13:47:50	0	disabled_ratio_field is neither a constant nor a field in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will do nothing about it.
2017-12-06T13:47:50	0	aggregation: Convert the aggregation layer to the analysis layer
2017-12-06T13:47:50	0	ANALYSIS : Hazard preparation
2017-12-06T13:47:50	0	hazard: use_same_projection_as_aggregation: True
2017-12-06T13:47:50	0	hazard: Clip raster by analysis bounding box
2017-12-06T13:47:50	0	hazard: Classify continuous raster hazard
2017-12-06T13:47:50	0	hazard: Polygonize classified raster hazard
2017-12-06T13:47:50	0	hazard: Clip and mask hazard polygons with the analysis layer
2017-12-06T13:47:50	0	hazard: Cleaning the vector hazard attribute table
2017-12-06T13:47:50	0	Features which have been removed from hazard : 0
2017-12-06T13:47:50	0	We add an ID column in hazard
2017-12-06T13:47:50	0	Fields which have been removed from hazard : hazard_val
2017-12-06T13:47:50	0	hazard: Assign classes based on value map
2017-12-06T13:47:50	0	ANALYSIS : Aggregate hazard preparation
2017-12-06T13:47:50	0	hazard: Make hazard layer valid
2017-12-06T13:47:50	0	aggregation: Union hazard polygons with aggregation areas and assign hazard class
2017-12-06T13:47:50	0	Feature geometry error: One or more output features ignored due to invalid geometry.
2017-12-06T13:47:51	0	ANALYSIS : Exposure preparation
2017-12-06T13:47:51	0	exposure: use_same_projection_as_aggregation: True
2017-12-06T13:47:51	0	exposure: Smart clip
2017-12-06T13:47:51	0	exposure: Cleaning the vector exposure attribute table
2017-12-06T13:47:51	0	Features which have been removed from exposure : 0
2017-12-06T13:47:51	0	We add an ID column in exposure
2017-12-06T13:47:54	0	Fields which have been removed from exposure : ID District Subdistric Village Male Female HH F_0_4 F_5_6 F_7_9 F_10_12 F_13_14 F_15 F_16 F_17 F_18 F_19 F_20_24 F_25_29 F_30_34 F_35_39 F_40_44 F_45_49 F_50_54 F_55_59 F_60_64 F_65_Plus M_0_4 M_5_6 M_7_9 M_10_12 M_13_14 M_15 M_16 M_17 M_18 M_19 M_20_24 M_25_29 M_30_34 M_35_39 M_40_44 M_45_49 M_50_54 M_55_59 M_60_64 M_65_Plus F_Sc_7_12 F_Sc_13_15 F_Sc_15_17 M_Sc_7_12 M_Sc_13_15 M_Sc_15_17 F_15_NoSD F_15_SD F_15_SMP F_15_SMA F_15_PT M_15_NoSD M_15_SD M_15_SMP M_15_SMA M_15_PT F_Not_Mrd F_Mrd F_Divorce D_Vision D_Hearing D_Walking D_Memory D_PersCare P_5_Lit P_5_Lang Employed E_Agri E_Industry E_Trade E_Service E_Edu E_Health E_Business E_Labourer HH_wood HH_bamboo HH_dirt HH_other PLN_meter PLN_NoMete PLN_non PLN_non_e DW_bottle DW_home DW_retail DW_pump DWP_well DW_well DWP_spring DW_spring DW_river DW_rain DW_other HH_wc HH_septic HP_line HP_mob HP_both Internet SHM_member SHM_non SHM_cert SHM_other HH_Female HH_Elderly
2017-12-06T13:47:54	0	We noticed some counts in your exposure layer. Before to update geometries, we compute the original size for each feature.
2017-12-06T13:47:54	0	The size calculator is set to use Meters
2017-12-06T13:47:54	0	The impact function could not run because of a bug.
2017-12-06T13:47:59	0	****Problem
			
			    The following problem(s) were encountered whilst running the analysis.
			
			 - InvalidLayerError
			
			****Suggestion
			
			    You can try the following to resolve the issue:
			
			 - inasafe_fields has more fields than the layer exposure itself : set(['female'])
			
			*****Details
			
			    These additional details were reported when the problem occurred.
			
			 - inasafe_fields has more fields than the layer exposure itself : set(['female'])
			
			*****Diagnostics
			
			 1. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1419, in run self._run()
			 2. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
			 3. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1620, in _run self.exposure_preparation()
			 4. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
			 5. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2226, in exposure_preparation self.debug_layer(self.exposure)
			 6. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1371, in debug_layer check_inasafe_fields(layer)
			 7. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 48, in check_inasafe_fields raise InvalidLayerError(message)
			
			
```

**Comment by Charlotte-Morgan** [comment]
Hmm - I think that is fine because I asked it to include female but did not set an attribute. Maybe a nicer error message is all that is needed here.

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry and @ismailsunni - I have more crash dumps today with related work on the same file.
Basically I am using one vector population data set and setting kw and options for different analysis runs. I am also changing the title so my analysis details have some record of the data.
- ie only females and only some age groups
then males
then disabled etc
I get the feeling something is held in memory and clashes when I change the key words and title. 
The process runs but then crash dumps with no new layers in TOC and a flash of kw in the dock. No error messages

**Comment by Gustry** [comment]
Can you create a ticket for that? We might lose these comments on PR

**Comment by Charlotte-Morgan** [comment]
thanks @Gustry see #4750

**Pull request merged**
