### PR TITLE
Small tweaks pre release

### PR DESCRIPTION
**Pull request by timlinux**
Fix another failing test in windows. Use QGIS API for featurecount test in test_shake_grid.py rather

### What does it fix ?

* Funded by : DFAT
* Description : 

Fixes for windows test
Other tweaks coming

### CODE REVIEW

**Comment by Gustry** [comment]
Is-it normal that `safe/test/data/other/jakarta.gpkg` is updated in your PR ?

**Comment by timlinux** [comment]
PEP8 test set to fail on windows (on purpose):

2017-03-05 13_57_51-settings

PEP8 test set to pass on windows:

2017-03-05 14_00_51-inasafe - e__dev_python_inasafe - _safe_test_test_pep8 py - pycharm 2016 2

**Comment by timlinux** [comment]
> Is-it normal that safe/test/data/other/jakarta.gpkg is updated in your PR ?

@Gustry hmm no its unexpected - something in the test must be altering its state,,,,

**Comment by Gustry** [comment]
Maybe the test on windows is updating it. We never got it updated I guess on mac. Can you revert it ?

**Comment by Gustry** [comment]
Ah thanks, I just saw your new commit ;-)

**Comment by timlinux** [comment]
Ok for me to merge @Gustry ?

**Comment by timlinux** [comment]
I went ahead and merged - the changes should be low impact.

**Comment by Gustry** [comment]
I see you still updated safe/test/data/other/jakarta.gpkg
I will revert it. We will need to fix the test on windows.

**Pull request merged**
