### PR TITLE
add make command to run tests in docker

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?
* Ticket: #
* Funded by: DFAT
* Description: While my test environment is broken, I'm using docker.

Running all tests in local, I have one failing test, in 4 mins 30 seconds:
```
======================================================================
FAIL: test_minimum_needs_outputs (report.test.test_impact_report.TestImpactReport)
Test generate minimum needs section.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests_directory/safe/report/test/test_impact_report.py", line 1035, in test_minimum_needs_outputs
    expected_context.strip(), actual_context.strip(), message)
AssertionError: For this analysis, the following displacement rates were used: Wet - 90%, Dry - 0%
For this analysis, the following displacement rates were used: X - 100%, IX - 100%, VIII - 100%, VII - 100%, VI - 100%, V - 0%, IV - 0%, III - 0%, II - 0%, I - 0%

----------------------------------------------------------------------
Ran 324 tests in 276.267s

FAILED (failures=1, skipped=13, expected failures=10)
Finished running test test_suite.test_package.
```

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
Going to merge this, feel free to review, I can update later

**Comment by ismailsunni** [comment]
Thanks @Gustry , very nice. I tried in my laptop also, I got the same result. But if I ran the failed unit test separately, it pass. Perhaps there is reference or object that has been changed by other unit test.

**Comment by ismailsunni** [comment]
I think the problem is in `test_earthquake_population_without_aggregation`. If I ran it before `test_minimum_needs_outputs`, it will the error. But if I skip that test, it will pass.
Run
screen shot 2017-10-19 at 07 29 11

Skipped
screen shot 2017-10-19 at 07 29 35

**Comment by ismailsunni** [comment]
Ouch, there is already a note from @myarjunar 

```
# TODO: find out why this test makes test_minimum_needs_outputs failing
# if this test runs in travis before test_minimum_needs_outputs. We change
# the filename at the moment so it will run after test_minimum_needs_outputs.
```

See: https://github.com/inasafe/inasafe/blob/develop/safe/report/test/test_impact_report_earthquake.py#L34

Perhaps we should put it in the failed test :D

**Pull request merged**
