### PR TITLE
update multi-buffer icon

### PR DESCRIPTION
**Pull request by myarjunar**
#3367

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks @MariaSolovyeva and @myarjunar

@myarjunar Please reference the ticket too.

**Comment by myarjunar** [comment]
#3367

**Comment by Gustry** [comment]
Ahah thanks @myarjunar I mean the ticket for this PR : https://github.com/inasafe/inasafe/issues/3704 ;-)

**Comment by myarjunar** [comment]
Argh sorry @Gustry , what I know is ticket = issue :joy: thanks!

**Pull request merged**
