### PR TITLE
fix issue #3787: zero rows should not be displayed

### PR DESCRIPTION
**Pull request by lucernae**
- Zero rows should not be displayed in aggregation table
- fix issue #3792: Value Error when generating infographic
- make analysis exited if report generation encountered an error

### CODE REVIEW

**Comment by lucernae** [comment]
Ah, strange error in impact_function. It seems, no 'inasafe_fields' in the keywords.
@Gustry could you look at this too?

**Comment by Gustry** [comment]
I will try during the week-end

**Comment by Gustry** [comment]
Can you update the conflict ?

I tried your PR on my mac, the test is passing. I already relaunched travis, no luck.
If the test is passing on your mac too, can you make many commits ? To see which commit is failing on travis. Do you want me to try @lucernae ?

**Comment by lucernae** [comment]
Yes, it passes in my mac too. I will update the PR then.

**Comment by lucernae** [comment]
I described the issue in #3821 . It is in current develop, at first glance I thought it is something you're more familiar with @Gustry 😄 . The error is about inasafe_fields not found in the aggregation_preparation keywords.
It rise up in this PR because I removed some unit test with expectedFailure decorator.

**Comment by Gustry** [comment]
So can you please keep the expectedFailure decorator and merge your PR (so as to work on this test on my side). I'm going to fix the other ticket you created

**Comment by lucernae** [comment]
Ah, all right if that's ok with you.

**Comment by Gustry** [comment]
Yes please. I can work on that this afternoon if it's merged.

It was this test : 'test_minimum_needs'

**Pull request merged**
