### PR TITLE
Add support for downloading PetaJakarta data

### PR DESCRIPTION
**Pull request by timlinux**
See #2471

Here is a summary of changes:

New icon (blue PJ icon) in the toolbar:

screenshot from 2015-11-23 12-11-53

Clicking it pops up this dialog:

screenshot from 2015-11-23 12-11-20

Which includes context help:

screenshot from 2015-11-23 12-11-28

After clicking OK and waiting a few seconds you get a new layer like this:

screenshot from 2015-11-23 12-11-44

Note the style is automatically created above and so are the keywords (see below).

screenshot from 2015-11-23 12-11-08
screenshot from 2015-11-23 11-42-00

### CODE REVIEW

**Comment by timlinux** [comment]
@Charlotte-Morgan care to comment about this feature? Can I merge it to develop?

**Comment by Charlotte-Morgan** [comment]
hi @timlinux 

I managed to get this error after only a couple of clicks

What I did to get this:
opened PJ downloader
opened help (without changing anything)
clicked ok (really wanted to go back and set options)
got warning that directory does not exists
clicked no to make directory

image

Lead to a less than friendly user experience :)

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\peta_jakarta_dialog.py", line 187, in accept
    self.require_directory()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\peta_jakarta_dialog.py", line 381, in require_directory
    raise CanceledImportDialogError()
CanceledImportDialogError


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, 313a6bc

Python path: ['C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\bin', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\arcpy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\ArcToolbox', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/AIFDR_ADMIN/.qgis2//python', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\inasafe', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', 'C:/AIFDR/AIFDR II - SDA/05_Jakarta Flood/01 Data/OSM']
```

**Comment by Charlotte-Morgan** [comment]
Some other thoughts:
I am wary of making something so 'site specific' but its going to be great so lets do it.
It would be great to make the default file name reflect the data and time (of the data) in the prefix and reporting period and areas as a suffix or allow the user to add a suffix

proposed file naming convention ( i just remembered you are allergic to capitals, but you get the idea)

ddMMMyy_hhmm_JakartaFlood_rw_3hr.shp
27NOV15_1430_JakartaFlood_rw_3hr.shp

time in 24hrs (local time)
rw or kel or kec (kelurahan or kecamatan for village or sub district)

it would be great to have the date and time included in the title 
It would be great to populate the date key word automatically
If not in the file name then add a time keyword and handle both date and time that way
there are 2 fields in the data (count and flooded) and it appears that flooded is the binary flood affected field ...  really the default display should only show wet areas?
not sure what the count field is and how you chose the symbology. It would be good to check what the value range in this field might be - is it count of reports or number of hours ie max might be 6
symbology - can you add a border to the symbol.

Why all this:  I have downloaded 2 data sets with different time stamps and spatial scale yet they appear exactly the same in the display & in the key words.
I will show you the amazing mess of historical flood data I have; any automatic sensible file naming will change the world we live in :)

Nice stuff:
context help
downloads whole data set not limited to the QGIS window 
everything else is nice too :)

Thanks for doing this.

# cc
@iyan31 @samnawi @raniedwianugrah @elida 
As HOT flood experts, what do you think of this tool? Do you have any suggestions on how this will make life easier for DM during flood events?

**Comment by timlinux** [comment]
Hi

@Charlotte-Morgan wrote:

> I am wary of making something so 'site specific' but its going to be great so lets do it.

Ok I have removed it from the toolbar and tucked it away in the plugin menu - I agree it is quite specific. We could also make it a completely separate plugin, but I like the idea of InaSAFE being a one stop shop.

> It would be great to make the default file name reflect the data and time (of the data) in the prefix and reporting period and areas as a suffix or allow the user to add a suffix

The one down side to this is if you have set up a project you can just re-generate the shapefile data and e.g. print your map or what have you. How about I add an 'add timestamp to filename' option?


> proposed file naming convention ( i just remembered you are allergic to capitals, but you get the idea)
> ddMMMyy_hhmm_JakartaFlood_rw_3hr.shp
> 27NOV15_1430_JakartaFlood_rw_3hr.shp
> time in 24hrs (local time)
> rw or kel or kec (kelurahan or kecamatan for village or sub district)

Ok sounds fine, I will do that (with a toggle for the date in filename as mentioned above).

> it would be great to have the date and time included in the title 
> It would be great to populate the date key word automatically

Ok will do. Thanks very much for reviewing this.

**Comment by iyan31** [comment]
I support @Charlotte-Morgan ideas to put timestamp in filename since the nature of floods report is very dynamic. That is what I can think for now, will update if I have other thoughts later.

**Comment by timlinux** [comment]
Ok I have made a number of updates:

screen shot 2015-11-30 at 16 37 24

Added checkbox to include date/time in output filename.

screen shot 2015-11-30 at 16 31 44

* Dynamically set metadata title to include the date
* Dynamically set the metadata date/time stamp

Also:

* Updated context help
* Remove icon from the toolbar - it is only available in the InaSAFE plugin menu now
* Various refactoring and code cleanup

**Comment by timlinux** [comment]
@Charlotte-Morgan wrote:

> there are 2 fields in the data (count and flooded) and it appears that flooded is the binary flood affected field ... really the default display should only show wet areas?

The default display is a choropleth map based on number of tweets per polygon (``count``). Currently wet areas and dry areas are shown (dry are a very light blue). Are you wanting me to remove the dry areas completely from the map? Or even from the shapefile?

> not sure what the count field is

Count is the number of tweets per area as provided by PetaJakarta

> and how you chose the symbology.

Since I don't have a good idea of how many tweets there might be in 'full onslaught' mode, I made some (un?)intelligent guesses in order to create classes where each class is an order of magnitude than the one before it. Again, we can change this to some other scheme, no problem.

> It would be good to check what the value range in this field might be - is it count of reports or number of hours ie max might be 6

I believe it to be the number of tweets over the reporting period, but that is pure guessing on my part. You may well be correct that it is the number of hours that have tweets in them...we will need to investigate to find out if that is the case.

> symbology - can you add a border to the symbol.

Sure

**Comment by Charlotte-Morgan** [comment]
my expectation of 'future' data is that it will not have counts. I'm expecting classified data.
We need to think if we will download null data or only flood data and if we will only display flooded areas. We can talk to PJ team next Monday.

**Comment by timlinux** [comment]
@Charlotte-Morgan ok good - I am going to park it till then.

**Comment by timlinux** [comment]
Just to confirm that on chatting with PetaJakarta folks, API v2 will provide flooded / not flooded status and depth. I will update the symbology accordingly when the new API is available on the 15th

**Comment by timlinux** [comment]
Based on discussion with @Charlotte-Morgan we will leave this for 3.5 (I need to go and add a 3.5 milestone!) as the PetaJakarta API is not ready or stable yet...

**Comment by timlinux** [comment]
@Charlotte-Morgan I have made some tweaks to work with the new API. I have left the o level polygons in for now, but everything is semi-transparent in the symbology I have created (see below). I have also updated the symbology classes in the legend to match those published by PJ. I have taken away the elements not supported in API v2 (specifying time / duration / boundary level). I am going to merge this for 3.3 - we can tweak it later if needed. Hope thats ok!

Symbology example:

screen shot 2016-02-22 at 23 24 40

Legend:

screen shot 2016-02-22 at 23 32 16


Metadata:

screen shot 2016-02-22 at 23 34 56

Note that I set the layer to be a classified flood layer rather than a wet / dry layer.

**Comment by timlinux** [comment]
By the way these are the class mappings I did:

screen shot 2016-02-22 at 23 46 02

**Comment by timlinux** [comment]
@ismailsunni will you review and merge if the tests have passed so that the translations can be done for this? Thanks!

**Comment by ismailsunni** [comment]
LGTM

**Pull request merged**
