### PR TITLE
Batchrunner for version 4

### PR DESCRIPTION
**Pull request by ivanbusthomi**
Adapting batchrunner to work with the version 4 code.

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks for the PR @ivanbusthomi 
We made `pep8` compulsory. You can see the result in travis why it's failing : https://travis-ci.org/inasafe/inasafe/builds/182526316#L362

**Comment by Gustry** [comment]
The missing line is on that line : https://github.com/ivanbusthomi/inasafe/blob/20bfc16bf2599818ef87ebd22d9a11dec7a47a6f/safe/gui/tools/batch/scenario_runner.py#L138

**Comment by ismailsunni** [comment]
@ivanbusthomi you can also run `make pep8` from inasafe directory to see any PEP8 issue.

**Comment by Gustry** [comment]
Hi @ivanbusthomi 
We should release the beta version this week (tomorrow). Do you think you will finish this PR for the release ?

You can safely remove all your comments I think because we don't have IF ID anymore.

**Comment by ivanbusthomi** [comment]
Hi @Gustry,
I already fixed the PEP8, and added some function to toggle whether the scenario will be run in a new project or not.
I haven't rebase it to the current version of develop yet, should I do it?

And I noticed these line of code doesn't run, because after running a scenario , `global_status_flag` still return `False`
https://github.com/ivanbusthomi/inasafe/blob/20bfc16bf2599818ef87ebd22d9a11dec7a47a6f/safe/gui/tools/batch/scenario_runner.py#L60
But I still receive the analysis result layers

**Comment by Gustry** [comment]
Hum, what happened to this PR with a lot of commits ?
I heard that you already talked to @ismailsunni about the signal. Did you get some hints ?

**Comment by ivanbusthomi** [comment]
Hi @Gustry maybe it is because I rebased the code to the current version of develop. Or maybe I messed up with the rebasing?

**Comment by Gustry** [comment]
Let's close this one. The new PR : #3508

**Pull request closed without merging**
