### PR TITLE
Fix parsing date without timezones

### PR DESCRIPTION
**Pull request by lucernae**
For issue #2319

This is one of the issue caused by poorly normalized date format (without timezone).

### CODE REVIEW

**Comment by lucernae** [comment]
Added some platform switch for Windows timezone mapping.

It will be easier to solve if we can import tzlocal. But tzlocal was not included in QGIS python lib.

**Comment by ismailsunni** [comment]
LGTM

**Comment by NyakudyaA** [comment]
LGMT

**Comment by NyakudyaA** [comment]
On windows it still gives error.
Data used: [http://earthquake.usgs.gov/earthquakes/shakemap/atlas/shake/200712081955/download/grid.xml](url)

The error on windows is:
`GridXmlParseError: Failed to parse grid file. 'SE Asia Standard Time' 
Traceback (most recent call last):
  File "C:/Users/admire/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shakemap_converter_dialog.py", line 184, in accept
    algorithm_filename_flag=True)
  File "C:/Users/admire/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 920, in convert_mmi_data
    algorithm_filename_flag=algorithm_filename_flag)
  File "C:/Users/admire/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 144, in __init__
    self.parse_grid_xml()
  File "C:/Users/admire/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 314, in parse_grid_xml
    'Failed to parse grid file.\n%s\n%s' % (e.__class__, str(e)))
GridXmlParseError: Failed to parse grid file.
'SE Asia Standard Time'`

**Comment by timlinux** [comment]
@NyakudyaA can you confirm you tested on @lucernae 's branch?

**Comment by NyakudyaA** [comment]
image

Yes @timlinux

**Comment by timlinux** [comment]
Ok thanks @NyakudyaA

**Pull request merged**
