### PR TITLE
Fix 4200

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: #4200
* Funded by: DFAT
* Description: 
   - Add unit test to replicate the problem
   - Add clear to make sure the state of the field mapping step is clean.

cc @samnawi @felix-yew @ivanbusthomi

### CODE REVIEW

**Comment by samnawi** [comment]
LGTM

**Comment by felix-yew** [comment]
Hi mas ismail - I get the result but show 0
image

**Comment by ivanbusthomi** [comment]
Hi mas @ismailsunni - I can confirm that I got the same result as mas @felix-yew

**Comment by Gustry** [comment]
For code, it's ok

**Comment by ismailsunni** [comment]
@felix-yew and @ivanbusthomi the different number is caused by the type of field (Integer vs Integer64. But we still don't know yet, why. I will merge this PR since it's not related to the problem.

**Pull request merged**
