### PR TITLE
Reporting additional needs

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix?
* Ticket: #4320 
* Funded by: DFAT
* Description: Add the additional minimum needs back to the report.
selection_113

selection_114

cc @felix-yew @timlinux @Charlotte-Morgan

### CODE REVIEW

**Comment by felix-yew** [comment]
Hi @myarjunar - When I try your PR, I got something just like this 
image

```
Problem
The following problem(s) were encountered whilst running the analysis.

TypeError
Suggestion
You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.

QgsExpressionContextUtils.setProjectVariables(dict-of-QString-QString): argument 1 has unexpected type 'dict'
Diagnostics

In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 903, in layer_changed self.set_provenance_to_project_variables(provenances)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1459, in set_provenance_to_project_variables self.remove_provenance_project_variables()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1476, in remove_provenance_project_variables QgsExpressionContextUtils.setProjectVariables(existing_variables)
```

**Comment by Gustry** [comment]
This error is for @ismailsunni

**Comment by ismailsunni** [comment]
Looking at the error message, it looks like I have fixed it in https://github.com/inasafe/inasafe/pull/4342

**Comment by ismailsunni** [comment]
@myarjunar sorry, rebase this PR from develop, so that @felix-yew can test it.

**Comment by felix-yew** [comment]
image
LGTM :+1:

**Pull request merged**
