### PR TITLE
regarding issue #3607: change calculation of additional rice

### PR DESCRIPTION
**Pull request by lucernae**
### What does it fix ?
* Ticket #3607 
* Funded by : DFAT
* Description : change additional rice calculation

### CODE REVIEW

**Comment by lucernae** [comment]
Sample calculations:

Without rounding:
screen shot 2017-03-10 at 16 14 27

With rounding:
screen shot 2017-03-10 at 16 14 48


Formula that is being used:
22110 is the total displaced
3299 = 22110 * (0.024 + 0.026) * 550 * 7 * 0.1 / 129

**Comment by Gustry** [comment]
Can you update the post processor tree at the bottom of the file? Thanks

**Comment by fredychandra** [comment]
Hi @lucernae 

I try to calculate the extra rice as below. Please compare with the formula that you have shown above. I find a different result with your calculation. 

Simulation : 
Total Displaced "Jati"= 22200
Ratio Breastfeeding and Pregnant = (2,4% + 2,6%) = 5 %
Extra Rice need for BreastFeeding and Pregnant Women is 0,3876 Kg/day

Extra Rice per week = 22200 * 0.05 * 0,3876 Kg/day * 7 (days)
                                = 3011.652 Kg/week
                                = 3011,7 Kg/week (Rounded)

**Comment by lucernae** [comment]
Hi mas @fredychandra , sorry. My mistake, I read the extra calories as 550Kkal instead of 500. 👍

**Comment by lucernae** [comment]
For @Gustry , I think the execution order doesn't change. Semantically it should be calculated after gender postprocessors.

**Comment by Gustry** [comment]
The order doesn't change, but the branch is not the same in the tree.
I think you need to remove one tab, it will be like this L789 : 
```
# |      |--- gender
# |      |--- hygiene packs
# |      |--- additional rice
```
This is cosmetics, but is usefull to quickly see which processor needs to run before.

**Comment by lucernae** [comment]
Ah you mean that one. What does the tree represents? Is it dependencies? If that is so, then I only need to move additional rice and let hygiene packs be.

**Pull request merged**
