### PR TITLE
#3178 work on hazard class mappings to definitions

### PR DESCRIPTION
**Pull request by Gustry**
This PR supersede : https://github.com/inasafe/inasafe/pull/3205 from @timlinux

### CODE REVIEW

**Comment by ismailsunni** [comment]
LGTM...

One question, what is the purpose of adding class_value? To be put in the hazard_class field?

**Comment by Gustry** [comment]
Just a link for me : https://github.com/inasafe/inasafe/issues/2920#issuecomment-229874044

@timlinux Any reason why we didn't want to use a string for the hazard_class_field ?

**Comment by timlinux** [comment]
Yeah I guess we can store just the class (string)

**Comment by Gustry** [comment]
Ok, I will do.
@timlinux Can we also remove vector/hazard difference for hazard_classification ?

**Comment by Gustry** [comment]
See the other PR : https://github.com/inasafe/inasafe/pull/3276

**Pull request closed without merging**
