### PR TITLE
Add hazard_classfications in hazard. PEP8.

### PR DESCRIPTION
**Pull request by ismailsunni**
Introduce hazard_classifications to hazard defintions

### CODE REVIEW

**Comment by Gustry** [comment]
LGTM.
You are lucky, GIT is so clever that it can manage the pep8 conflict ;-) (we did the same fix)

**Comment by ismailsunni** [comment]
@Gustry 
Yes, we can. For example a classification has 3 classes (low, medium, high) where the other has 4 classes (very low, low, medium, high) for the same hazard.

**Comment by Gustry** [comment]
but we agree that we don't support this now ?
I mean I can see that all our lists have only one classification inside, like : 
```
'vector_hazard_classifications': [generic_vector_hazard_classes],
'raster_hazard_classifications': [generic_raster_hazard_classes],
'hazard_classifications': [generic_hazard_classes],
```

**Comment by Gustry** [comment]
OK LGTM

**Comment by ismailsunni** [comment]
@Gustry 
> but we agree that we don't support this now ?

Well, we just need to add more classification to the list. Since now we only have one per hazard, I only put one for each.

**Pull request merged**
