### PR TITLE
Added worldpop population integration

### PR DESCRIPTION
**Pull request by Samweli**

### CODE REVIEW

**Comment by timlinux** [comment]
Thanks so much @Samweli - we will need a little time to review this so I am queuing it for the next release ok? We will test it and give you feedback soon.

**Comment by Samweli** [comment]
Sure, it is ok @timlinux, in the meantime i will be working on finding the best way to get data by using aggression areas. 
Cheers.

**Comment by ismailsunni** [comment]
Hi @Samweli 
Can you also add unit test for the PR?

**Comment by Gustry** [comment]
@Samweli I saw you copy/paste the code from `safe/utilities/file_downloader.py`.
Is-it possible to change the file_downloader to use your new requests.py ? So we can remove duplication of code.

**Comment by Samweli** [comment]
Noted @Gustry, working on it.

**Comment by Gustry** [comment]
Thanks, let me know if you have any question.

**Comment by timlinux** [comment]
@Samweli Do you have any updates on this - it would be great to have it ready for merge by next week (7 Nov) so that we can include it in our beta release for v4.0

**Comment by timlinux** [comment]
Update from @Samweli

**Comment by timlinux** [comment]
I heard from @

**Comment by timlinux** [comment]
I heard from @Samweli and it seems they don't have capacity to keep on with this work right now. We will need to finish this off ourselves

**Comment by timlinux** [comment]
Closing this off - please reopen if you like to bring this back to our attention.

**Pull request closed without merging**
