### PR TITLE
Use custom logo and north arrow. Fix #4671.

### LINKED ISSUE #4671: Custom logo doesn't appear in map report
### Problem
I've set a custom organisation logo in the InaSAFE options dialog:
image

It appears in the InaSAFE Dock:

image

But doesn't appear in any of the PDF or HTML reports. 

image

### Expected Behaviour

Custom logo to appear on the reports in place of the default supporters logo

### Environment
* InaSAFE : 4.2.4
* QGIS : 2.18.6
* OS : Windows 7 (64-bit)
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: #4671 
* Funded by: DFAT
* Description: 
   - Use custom logo (from the setting)

### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [x] Request someone to review or test your PR

### CODE REVIEW

**Comment by ivanbusthomi** [comment]
it worked in the dock
image

and in the report
image

**Comment by ivanbusthomi** [comment]
Edit:
the disclaimer in the report also changed using the custom one. But in the dock it still using the default

image

image

**Comment by ismailsunni** [comment]
> the disclaimer in the report also changed using the custom one. But in the dock it still using the default

What do you mean in the dock? Is it when InaSAFE loaded (not doing anything yet) ?

**Comment by ivanbusthomi** [comment]
> Is it when InaSAFE loaded (not doing anything yet) ?

Yes, it is when the disclaimer information is shown in the dock panel. Usually when we do not do anything yet

**Comment by ismailsunni** [comment]
Hi @ivanbusthomi 
I just added another commit to make it also shows on in the Dock.

**Comment by ismailsunni** [comment]
Thanks @Gustry 

I have added them in the `default_settings.py`.

I really hope we can make these setting things like our definition, so that we know that a key does exist and has default value.

**Pull request merged**
