### PR TITLE
Fix 2846 none sym diff

### PR DESCRIPTION
**Pull request by ismailsunni**
For #2846 errors:
- `TypeError, QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'`
- Includes #2854

### CODE REVIEW

**Comment by ivanbusthomi** [comment]
mas @ismailsunni I've checked it in case number 3 (earthquake vs landcover). Without aggregation works,the AttributeError is gone. With aggregation, I still got the TypeError
```
The following problem(s) were encountered whilst running the analysis.
TypeError

These additional details were reported when the problem occurred.
An exception occurred when running the impact analysis.
QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'

In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 678, in run_analysis self._prepare()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 851, in _prepare self.aggregator.deintersect_exposure()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 494, in deintersect_exposure agg_attribute)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 1652, in _intersect_exposure_with_aggregation out_feature.setGeometry(out_geom)
```

**Comment by ismailsunni** [comment]
Hi @ivanbusthomi 
Thanks for checking the PR. I have pushed another commit to "fix" the issue. Actually, I just catch the error, and ignore it. It looks strange though the result.
Please check and perhaps compare it with the single part that you made before.

**Comment by ivanbusthomi** [comment]
mas @ismailsunni 
I've done the checking again. The process run well, and i didnt find any error message for case number 3 - 6 in #2846 . But for case number 2, I still get another _Type Error_ message like this one :
```
The following problem(s) were encountered whilst running the analysis.
TypeError

These additional details were reported when the problem occurred.
An exception occurred when running the impact analysis.
can't multiply sequence by non-int of type 'float'

In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 679, in run_analysis self._impact = self._calculate_impact()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1411, in _calculate_impact result_layer = self.run()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\generic\classified_polygon_people\impact_function.py", line 163, in run impact_fields)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\generic\classified_polygon_people\impact_function.py", line 422, in evaluate_impact writer)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\generic\classified_polygon_people\impact_function.py", line 498, in assign_impact_level area_population_attribute)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\generic\classified_polygon_people\impact_function.py", line 665, in calculate_population_number (target_area / total_area) * population_total)
```

**But** since this PR is specific for the `TypeError, QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'` ,  I think it **looks good to me**
:smile:

**Comment by ivanbusthomi** [comment]
@ismailsunni 

After testing this PR on case number 2 in Ubuntu 12.04 using QGIS 2.8.2, I got another kind of TypeError and i'm not sure wether to put the details here or in the ticket. So I'll just put the details here:
```
The following problem(s) were encountered whilst running the analysis.
TypeError

These additional details were reported when the problem occurred.
An exception occurred when running the impact analysis.
in method 'Open', argument 1 of type 'char const *'

In file "/home/busthi/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 678, in run_analysis self._prepare()
In file "/home/busthi/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 845, in _prepare self.hazard.qgis_layer(), self.exposure.qgis_layer())
In file "/home/busthi/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 443, in set_layers self.safe_layer = safe_read_layer(self.layer.source())
In file "/home/busthi/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 30, in read_layer return Vector(filename)
In file "/home/busthi/.qgis2/python/plugins/inasafe/safe/storage/vector.py", line 172, in __init__ self.read_from_file(data)
In file "/home/busthi/.qgis2/python/plugins/inasafe/safe/storage/vector.py", line 459, in read_from_file fid = ogr.Open(filename)
In file "/usr/lib/python2.7/dist-packages/osgeo/ogr.py", line 4048, in Open return _ogr.Open(*args, **kwargs)
```

**Comment by timlinux** [comment]
Please merge here and then continue fixing after 3.4 is out

**Pull request merged**
