### PR TITLE
use the official QGIS docker base image for travis

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?

use the official QGIS docker base image for travis

WIP:
* [x] Use the 3.4 tag, waiting for https://github.com/qgis/QGIS/pull/8500

### Checklist:

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
> The command "docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test_suite.test_package"" exited with 1.

@elpaso I can have a look why it failed, but maybe you have a idea.

Also, according to the log:
```
QGIS Test Runner Inside - starting the tests ...
QGIS Test Runner - Trying to import test_suite.test_package
Traceback (most recent call last):
  File "<string>", line 70, in __get_test_function
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test_suite.test_package'; 'test_suite' is not a package
QGIS Test Runner - Trying to import test_suite
```

Maybe the error message can be skipped or improved? Maybe just a warning? Because I was wondering if it was not a fatal error, but it seems that it's still working after that.

Thanks for doing this work @elpaso

**Comment by elpaso** [comment]
@Gustry that's not an error or a warning, it's just debugging output.
See: https://github.com/qgis/QGIS/blob/master/.docker/qgis_resources/test_runner/qgis_testrunner.py#L73
and https://github.com/qgis/QGIS/blob/master/.docker/qgis_resources/test_runner/qgis_testrunner.py#L84

Btw, I'm fine with hiding them now, feel free to make a PR.

**Comment by elpaso** [comment]
@Gustry I think I know what's going on here, I'll fix the runner

**Comment by elpaso** [comment]
This should do the trick, I've added tests for the exit codes, let's see if travis is happy:
https://github.com/elpaso/QGIS/commit/287554332b80d85441dc889388e3a59305751b01#diff-862a8d21dcff19a26be6cb27f9f87223R22

**Comment by Gustry** [comment]
Great, it works @elpaso for the master branch. Travis is now waiting the 3.4 tag on docker hub ;-)

**Comment by elpaso** [comment]
> Travis is now waiting the 3.4 tag on docker hub ;-)

I'm waiting too, it's not on me.

Btw, I'd like you to have a look to some small changes I've been testing here:
https://github.com/qgis/QGIS/pull/8525/files

**Comment by Gustry** [comment]
> Btw, I'd like you to have a look to some small changes I've been testing here:
https://github.com/qgis/QGIS/pull/8525/files

Should I switch to elpasso/qgis:latest?

**Pull request merged**
