### PR TITLE
Improve report table

### PR DESCRIPTION
**Pull request by lucernae**
### What does it fix ?
* Tickets:
   - #2691
   - #3898
* Funded by : DFAT
* Description : 
  - fix issue #2691
  - add separate background highlight in detailed report
  - capitalize headers

### CODE REVIEW

**Comment by lucernae** [comment]
Sample of highlighted affected column with double header:
screen shot 2017-02-21 at 00 05 14

**Comment by timlinux** [comment]
Beautiful work @lucernae ! I wonder if the highlight is not a bit too heavy? Perhaps just putting an outline in charcoal around the group might look better?

**Comment by timlinux** [comment]
Hmm maybe that will be tricky since you deal with it cell by cell I guess - perhaps just a lighter accent colour would work well for now....

**Comment by Gustry** [comment]
It rocks @lucernae  !
I agree, a lighter color will do the trick I think

**Comment by lucernae** [comment]
@timlinux @Gustry could you review definitions/units.py later?
I added 'measure' key because I needed words like 'Length' (something that we measure) in the report.

**Comment by lucernae** [comment]
Is this lighter now?
screen shot 2017-02-21 at 02 34 33

Or, well since we can use css, we can do this too if you prefer:
screen shot 2017-02-21 at 03 21 53

Or both:
screen shot 2017-02-21 at 03 22 53

**Comment by lucernae** [comment]
The previous one seems to be not a good example. Actually, if there is a not affected group, it will show up something like this:

screen shot 2017-02-21 at 03 32 13

We could also styled each group if you want (e.g, give a different background color).

**Comment by ismailsunni** [comment]
Looks Beautiful For Me !!

**Comment by Charlotte-Morgan** [comment]
hey @lucernae - this looks really neat.
The only other think in the standard is the title for the table - ie what is the table about.
But for adding double headers and highlighting - this is great. LVGTM

**Comment by timlinux** [comment]
Can we go with this one @lucernae

**Comment by lucernae** [comment]
@Charlotte-Morgan Can you point out what's still missing?
I did assumed that the table title is the one in blue.
Maybe that's not what you meant?
screen shot 2017-02-21 at 00 05 14

**Comment by lucernae** [comment]
I will merge this for now and have the table title taken care in separate PR.

**Pull request merged**
