### PR TITLE
Set transparency to 0 for all style per #2529

### PR DESCRIPTION
**Pull request by ismailsunni**
For #2529

### CODE REVIEW

**Comment by samnawi** [comment]
mmm.... why all of the unaffected area become to white color?
image

**Comment by Charlotte-Morgan** [comment]
I don't think this is a good solution because we need to be able to draw the raster over other layers and  'see through' the areas with 0

**Comment by ismailsunni** [comment]
@Charlotte-Morgan @samnawi 
So, we only set transparent = 100 for 0 value in the impact layer? And, if the value is not 0, we set transparent = 0

**Comment by Charlotte-Morgan** [comment]
i have another solution which i put in the ticket #2529

**Pull request closed without merging**
