### PR TITLE
fix #2896

### LINKED ISSUE #2896: AggregationError when running Earthquake raster hazard vs Building
### Problem
I run analysis using the continuous raster earthquake hazard vs building polygon in InaSAFE 3.4.0 on QGIS 2.14.1 but I got an aggregation error, eventhough i did not load any aggregation layer. When I tried adding an aggregation layer, the problem still persist. Here are the error codes that i got:
```
PROBLEM
The following problem(s) were encountered whilst running the analysis.
AggregationError

SUGGESTION
You can try the following to resolve the issue:
Aggregation error occurred.

DETAILS
These additional details were reported when the problem occurred.
No attribute "safe_ag" was found in the attribute table for layer "Estimated buildings affected". The impact function must define this attribute for postprocessing to work.
Aggregation error occurred.

DIAGNOSTICS
```
**Note** that diagnostic section was empty. This is what i got in InaSAFE log panel
```
2016-06-02T18:09:18	0	Search path: C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg\shapely\DLLs;C:\PROGRA~1\QGISES~1\apps\Python27\DLLs;C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\numpy\core;C:\PROGRA~1\QGISES~1\apps\qgis\bin;C:\PROGRA~1\QGISES~1\apps\Python27\Scripts;C:\PROGRA~1\QGISES~1\bin;C:\Windows\system32;C:\Windows;C:\Windows\WBem
2016-06-02T18:09:18	0	Path for gdalwarp: ['C:\\PROGRA~1\\QGISES~1\\bin\\gdalwarp.EXE']
2016-06-02T18:09:18	0	"C:\PROGRA~1\QGISES~1\bin\gdalwarp.EXE" -q -t_srs EPSG:4326 -r near -cutline c:\users\busthi\appdata\local\temp\inasafe\2016-06-02\busthi\work\extent__rmxih.kml -crop_to_cutline -ot Float64 -of GTiff "D:/Ivan Busthomi/_data/EQ 160602/hazard/latest_eq.tif" "c:\users\busthi\appdata\local\temp\inasafe\2016-06-02\busthi\work\clip_t5fhcm.tif"
2016-06-02T18:09:23	0	Running earthquake building impact
2016-06-02T18:09:29	0	Do aggregation
2016-06-02T18:09:29	0	Removing this attributes: [0, 1, 2, 3]
2016-06-02T18:09:29	0	Skipping postprocessing due to:     No attribute "safe_ag" was found in the attribute table for layer "Estimated buildings affected". The impact function must define this attribute for postprocessing to work.
			
2016-06-02T18:09:29	0	    No attribute "safe_ag" was found in the attribute table for layer "Estimated buildings affected". The impact function must define this attribute for postprocessing to work.
```

I've encountered this problem earlier before the release of InaSAFE 3.4.0, but somehow I couldn't manage to replicate in another machine. I mentioned the problem earlier in https://github.com/inasafe/inasafe/issues/2879#issuecomment-222605869, but at that time the problem only occured in 2.8.8 while 2.14.1 worked just fine.

When I tried using the earthquake data in _West Sumatra_ data package from data.inasafe.org, it works fine. I tried running it in Ubuntu 12.04, instead of getting the same error message like i mentioned above, here is what i got:
```
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1157, in accept
    self.show_next_analysis_extent()
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2099, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2171, in validate_extents
    impact_function = self.prepare_impact_function()
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1260, in prepare_impact_function
    impact_function.hazard = self.get_hazard_layer()
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/continuous_rh_classified_ve.py", line 46, in hazard
    ImpactFunction.hazard.fset(self, value)
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 363, in hazard
    self._hazard = SafeLayer(convert_to_safe_layer(layer))
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 463, in convert_to_safe_layer
    return safe_read_layer(layer.source())
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 28, in read_layer
    return Raster(filename)
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/storage/raster.py", line 112, in __init__
    self.read_from_file(data)
  File "/home/busthi/.qgis2/python/plugins/inasafe/safe/storage/raster.py", line 187, in read_from_file
    fid = self.fid = gdal.Open(filename, gdal.GA_ReadOnly)
TypeError: in method 'Open', argument 1 of type 'char const *'

Python version:
2.7.3 (default, Jun 22 2015, 19:44:33) 
[GCC 4.6.3]

QGIS version:
2.8.2-Wien Wien, exported

Python path: ['/usr/share/qgis/python/plugins/processing', '/usr/share/qgis/python', u'/home/busthi/.qgis2/python', u'/home/busthi/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-installer', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/busthi/.qgis2//python', '/home/busthi/.qgis2/python/plugins/mmqgis/forms', '/home/busthi/.qgis2/python/plugins/inasafe', '/home/busthi/.qgis2/python/plugins/inasafe/safe_extras/parameters', '/home/busthi/.qgis2/python/plugins', '/home/busthi/.qgis2/python/plugins/inasafe/safe_extras', '/usr/share/qgis/python/plugins/fTools/tools']
```

### Expected Behaviour
It should works without problem.

### Environment
* InaSAFE : 3.4.0
* QGIS : 2.14.1 (also occured in 2.8.8)
* OS : Windows (with another error occured in Ubuntu 12.04)
* Data used : I used the data in West Sumatra
  * Exposure : Padang_Buildings_WGS84.shp (West Sumatra data)
  * Hazard : 2/06/2016 Raster Earthquake :point_right: [hazard.zip](https://github.com/inasafe/inasafe/files/295463/hazard.zip) :point_left: 
the data was created by converting grid.xml earthquake data from inasafe realtime into raster file
  * Aggregation : Padang_Village_Boundary_WGS84.shp (West Sumatra data)

### Proposed Solution
make it happy

____
**CC**: @felix-yew @samnawi @Charlotte-Morgan @ismailsunni @Gustry @timlinux

### PR DESCRIPTION
**Pull request by lucernae**

### CODE REVIEW

**Comment by Gustry** [comment]
@lucernae It could be nice if you can write a small sentence in your commit, if we don't want to open the ticket to know what you are fixing.

**Comment by ismailsunni** [comment]
LGTM,
Please test @ivanbusthomi 
And +1 for @Gustry 's comment

**Comment by lucernae** [comment]
Haha, I even put it inside the source code, man. I thought it was a good practice to link it to the actual ticket, so everyone should look at it.

**Comment by Gustry** [comment]
Yes, it's a good idea to comment the code, to put the ticket number in the commit. It's also good to put the ticket number in the comment. But I'm also using `git log` sometimes.

**Comment by Gustry** [comment]
I'm not against a merge, the other PR #2901 has already been merged without commit message ;-)

**Pull request merged**
