### PR TITLE
Modify structure class mapping. 

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
New definitions, new order.
#2721

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
@Gustry @timlinux @easmetz @harrymahar please review

**Comment by Gustry** [comment]
Thanks, LGTM

**Comment by Charlotte-Morgan** [comment]
Ouch - my mistake.
This PR also has #2764 notes and actions for tsunami IF

**Comment by ismailsunni** [comment]
LGTM

**Pull request merged**
