### PR TITLE
use the main workflow for EQ on population analysis

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?
* Ticket: #4249 
* Funded by: DFAT
* Description: use the main workflow for EQ on population analysis

Work in progress

### CODE REVIEW

**Comment by Gustry** [comment]
@timlinux @Charlotte-Morgan So what do we do with the 'allow resample' option in population keywords? Should we remove it? Or should we keep the algorithm about raster alignment?

**Comment by timlinux** [comment]
> @timlinux @Charlotte-Morgan So what do we do with the 'allow resample' option in population keywords? Should we remove it? Or should we keep the algorithm about raster alignment?

We can remove the allow resample and raster alignment options / logic.

**Comment by Gustry** [comment]
Ok, this PR needs a review.
I have some differences in results (total number of people) using the EQ function in InaSAFE 4.1 and this new one in 4.2. I can check deeper. I will appreciate feedback from @felix-yew about this new way to compute an EQ analysis.

**Comment by Gustry** [comment]
I'm going to merge it. I will do some more testing. At least we are now using the same GIS workflow. Maybe the previous one was not correct. @felix-yew Will you do some testing?

**Pull request merged**
