### PR TITLE
[WIP] Population in place

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: Part of #4483 
* Funded by: DFAT
* Description: 
   - Adding exposed population post processor. But I still can't see it in the  Exposure Summary Table.
   - Moreover I get the same value for population for all feature in the Exposure Summary Table
screen shot 2017-12-14 at 11 27 56

Can you give me some clue @Gustry ?

### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [x] Request someone to review or test your PR

### CODE REVIEW

**Comment by ismailsunni** [comment]
Hi @myarjunar 
I have finished with this PR. Now, we got something like this in the exposure summary
screen shot 2017-12-21 at 13 43 57

I think you can make the reporting to show the exposed population from that table above. I tried, but I am didn't succeed.

Btw, I have also fixed my two problems above.

**Comment by Gustry** [comment]
> Adding exposed population post processor. But I still can't see it in the Exposure Summary Table.
Moreover I get the same value for population for all feature in the Exposure Summary Table

Is-it still two issues?

**Comment by ismailsunni** [comment]
> Is-it still two issues?

No, I have fixed them like I said in my  previous comment.

**Comment by Gustry** [comment]
Sorry I didn't help you to fix them 7 days ago ;-)

**Comment by ismailsunni** [comment]
@Gustry You did help me yesterday :D

**Comment by ismailsunni** [comment]
Anyway, to make thing move faster, I will merge this PR first, and try again to fix the reporting.

**Pull request merged**
