### PR TITLE
update terminology about output layers

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?
* Ticket: #3726 
* Funded by: DFAT
* Description: update terminology about output layers

* [x] Check the ticket is correct 
* [x] Update filenames too

### CODE REVIEW

**Comment by ismailsunni** [comment]
Let me know if you have finished this. I need it for the provenance. :)

**Comment by Gustry** [comment]
@ismailsunni do you think my last commit is OK? I'm updating keys in definitions.
I'm waiting for travis to have a look.

**Comment by ismailsunni** [comment]
Oops, sorry, I missed this PR because the label is `In Progress`.
LGTM. Just need to fix the travis.

**Comment by Gustry** [comment]
So no problem to update the key? I'm afraid of side effect. Especially with your new variables where we will use the layer purpose to fetch the good layer. But hopefully we do this change both at the same time in 4.2
I was thinking about retro-compatbility, if you open an old analysis 4.1 in 4.2

**Comment by ismailsunni** [comment]
@Gustry 
What about just updating the name, but not the key. The key is invisible from the use. We also use varialble to access the key, so I think it should be fine if we do not update the key.

**Comment by Gustry** [comment]
Because the key is used for the filename:
screen shot 2017-07-27 at 10 05 25

And we wanted to update filename too, to remove the `aggregate_hazard_impacted` for instance.

**Comment by ismailsunni** [comment]
Ouch. I didn't aware that it was being used to name the file. If we need a retro-compability, we need to do name migration or something like that.

What about putting the filename in the layerpurpose definition. As a list. It will have new key and old key. If the file based on the new key is not available, check the old key. Not sure though

**Comment by Gustry** [comment]
Why do you want a name migration?
Did you see my latest commit in dock.py ? I know it's like a hack, but I think there is only this.

**Comment by ismailsunni** [comment]
Ah I see. Sorry, just re-read the whole code in that function again.
Yes, I think it's fine, we only use the key of layer_purpose of output layer to show the impact report, right?

**Comment by Gustry** [comment]
Travis should be happy now.

I would like to merge this as soon as possible today. I understood you agreed my PR if I read between lines ;-)
Still wondering if I won't have any side effects of this, but I think it should be fine. I think I will merge later today, but I will appreciate a review.

**Comment by Gustry** [comment]
Sorry, I re-read the thread, I saw the LGTM already, after my key update. Let's merge this so I can translate now

**Pull request merged**
