### PR TITLE
update layer id whenever IF is being serialized

### LINKED ISSUE #4942: Problem with provenance layer id on IF serialization
### Problem
IF serialization did not update the layer id in the provenance so the information is not reliable. We need to update the layer id whenever the IF is being serialized.

### Expected Behaviour
layer id representing the actual layer available 

### Environment
* InaSAFE : 
* QGIS : 
* OS : 

* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix?

* Ticket: fix #4942 
* Funded by: DFAT
* Description: 
  * update layer id whenever IF is being serialized

### Checklist:

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by myarjunar** [comment]
@Gustry  because it's being used by a lot of expressions and we want to keep the old behavior. So the id information needs to be reliable.

**Comment by Gustry** [comment]
But we should have use path or something else for these expressions. Something reliable with time, not having a temporary ID.

I think you need to backport this to the master branch now.

Or maybe it's time for me to be retired from InaSAFE ;D

**Comment by myarjunar** [comment]
I came with this solution because you said you want to keep the old behavior first (layer id in the provenance), but then check the layer path if the id doesn't exist :sweat_smile:  (I will add the code for checking the layer path)

> Or maybe it's time for me to be retired from InaSAFE ;D

nooooo :sob: :sob:

**Comment by Gustry** [comment]
I meant during our first implementation of using this ID ;-)

**Pull request merged**
