### PR TITLE
Fix error when loading InaSAFE in Bahasa Indonesia.

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: No ticket number
* Funded by: DFAT
* Description: 
   Fix this problem when loading InaSAFE in Bahasa.
```
2017-08-21T14:02:35    1    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 306, in startPlugin
                plugins[packageName] = package.classFactory(iface)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\__init__.py", line 73, in classFactory
                from safe.plugin import Plugin
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\__init__.py", line 28, in <module>
                from safe.common.custom_logging import setup_logger
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\__init__.py", line 28, in <module>
                from safe.common.custom_logging import setup_logger
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\common\custom_logging.py", line 31, in <module>
                from safe.common.utilities import log_file_path
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\common\utilities.py", line 27, in <module>
                from safe.utilities.rounding import (
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\utilities\rounding.py", line 9, in <module>
                from safe.definitions.units import unit_mapping, nominal_mapping
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\definitions\__init__.py", line 15, in <module>
                from safe.definitions.exposure import *
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\definitions\exposure.py", line 13, in <module>
                from safe.definitions.fields import (
              File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
                mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\definitions\fields.py", line 2365, in <module>
                affected_description=concepts['affected']['description']),
            KeyError: u'Affected_name'
```

### CODE REVIEW

**Comment by samnawi** [comment]
:+1: 
LGTM

**Comment by Gustry** [comment]
What do you want me to review here? ;-)

Why the TS file was out of sync?

**Comment by felix-yew** [comment]
yes, LGTM :+1:

**Comment by ismailsunni** [comment]
@Gustry sorry, muscle memory :D

**Pull request merged**
