### PR TITLE
Update translation for 4.3

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: No ticket
* Funded by: DFAT
* Description: 
   - Update translation for some string (for testing and reviewing)

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
I didn't finish translations! ;-)

**Comment by Gustry** [comment]
I'm nearly finished. I would appreciate if my translations can be here too

**Comment by ismailsunni** [comment]
@Gustry no worries. There will be second PR for the translations :D

**Comment by ismailsunni** [comment]
ah, ok, I just read you second comment.

**Comment by Gustry** [comment]
Thanks, French is back to 100%. We earned 1mb in GIT about binary files ;-)

**Comment by timlinux** [comment]
I added text for the metadata exporter - https://github.com/inasafe/inasafe/pull/4647 thanks

**Pull request merged**
