### PR TITLE
remove img from resources

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix?
* Ticket: #4514 #4638 
* Funded by: DFAT
* Description:  remove `img` from resources. actually, it was only `css` and `js` which has been being used.

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by ismailsunni** [comment]
What about the icon for the infographic or map (qpt) ? like north arrow?

**Comment by myarjunar** [comment]
> What about the icon for the infographic or map (qpt) ? like north arrow?

we are currently using an expression for that and the expressions are pointing into the resource in the plugin directory

**Comment by Gustry** [comment]
And QPT?

**Comment by myarjunar** [comment]
yes
selection_155

**Comment by Gustry** [comment]
Sorry, I don't understand the screenshot for QPT and QGIS Expressions ;-)
I guess what @ismailsunni and I meant was what about the QPT in the output folder. Is-it copied?

**Comment by myarjunar** [comment]
@ismailsunni ask me if we remove the img folder in the output resources dir,  how can we get the images for infographic and map report? the answer is we are using qgis expressions straight in the template. about the QPT in the output folder, what do you mean by copied? in this PR I didn't do anything for the report products, only to remove img directory from resources directory in the output directory. 

sorry if it's confusing :smiley:

**Comment by Gustry** [comment]
No problem ;-)
Can you fix and merge so?

**Comment by Gustry** [comment]
Also linked to ticket #4638

**Pull request merged**
