### PR TITLE
Update @akbargumbira's PR

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: #4410 
* Funded by: DFAT
* Description: 
  - Update @akbargumbira 's PR to master
  - Bump new version 4.2.4

### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [x] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
Ok, let's merge it and release the new version, no?

AFAIK, we didn't get any issue on develop and now the BNBP training is finished ;-)

Maybe update to 'final' to in this PR.

**Comment by ismailsunni** [comment]
@Gustry 
We can merge it, but I am not sure we need to release it, since it doesn't fix any bug. I am thinking to wait until we have some bugs that can be backporter to master. E.g. #4487

**Comment by Gustry** [comment]
We don;t need it for geosafe?

**Comment by ismailsunni** [comment]
Ah sorry, I am not aware that geosafe needs this PR to be merged and released. Now, I just realized, what we need to do for the pypy package (we should update it also).

Regarding releasing, I am still not sure to release it soon. But wait until we have more things to be backported and released, or if @lucernae starts working on the GeoSAFE migration (it seems he is on holiday).

**Comment by ismailsunni** [comment]
I will merge this since it seems the PR is good based on the discussion. And I need this PR to be merged for my another backport.

**Pull request merged**
