### PR TITLE
fix union algo from https://github.com/qgis/QGIS/pull/4037

### PR DESCRIPTION
**Pull request by Gustry**
This is the backport from @wonder-sk in QGIS.
This is not my code. I think we can just merge it.

### CODE REVIEW

**Comment by timlinux** [comment]
Since there is not much code, do you think it is worth updating it to follow our naming conventions? It is not very pythonic like this :-P I guess you might be motivated to keep it verbatim so that we can diff it against upstream. I'll leave the call to you, but at least let's add a comment indicating why we did not follow standards in this module. LGTM once you have made that call....

**Comment by Gustry** [comment]
Yes you are right.
I tried to stay close from the original code in case if we have to do this kind of things. I just did pep8 and some other cleaning.

I made a comment at the beginning : https://github.com/inasafe/inasafe/blob/develop/safe/gis/vector/union.py#L97
and at the end : https://github.com/inasafe/inasafe/blob/develop/safe/gis/vector/union.py#L278

**Comment by timlinux** [comment]
> I made a comment at the beginning :

Ah sorry I missed that...ok

**Comment by Gustry** [comment]
Ok I added some new comments about coding standards.

**Pull request merged**
