### PR TITLE
Reporting standards

### PR DESCRIPTION
**Pull request by timlinux**
Hi @easmetz and @Charlotte-Morgan 

Here is my first pass at creating the standards doc. It is written in markdown (same system we use for writing tickets) so it should be familiar. There is one caveat and that is that we cannot drag and drop images into the document like we do in a ticket. Quick workaround for that is to open an empty ticket, drag and drop an image into , the copy the created URL to your clipboard and paste it into the document.

In terms of workflow, I am proposing that we make a series of pull requests, covering one section of the document each. In my first mockup, I have synthesised content for the title for example.

Once the document has been fleshed out a bit, we can then start to take on PR's if we need to tweak the document as a whole.

We can apply these changes easily and immediately to the develop branch since they should not impact on any code so there should be low overhead in terms of test maintenance.

I'm happy to give a more detailed walk through e.g. on Skype if you need help to get the editing workflow right.

By the way, you can preview the document as it currently stands here:

https://github.com/timlinux/inasafe/blob/cd22b11a7e7720961593d9cbdd5ed8574b775621/docs/reporting-standards.md

Regards

Tim

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
hi @easmetz - @timlinux has made this pr with his idea for a better way to document the standards. Ie this would be the place to take the consolidated ideas from the RFC #2910 and would replace the idea of a wiki page #2840.  It would be great if you can take a look and see if this makes sense and if you think it would be easier to implement. Implementation of this approach would be a key task for you.
## cc
@RikkiWeber

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux - this looks like it will work to me.
Just to confirm my understanding:
-  all the content for the standards will be placed in a single mark down document as per the link above
- graphic elements should be loaded as images or entered as tables
- where should images be placed (I'm thinking of the docs work flow here)

**Comment by timlinux** [comment]
Hi @Charlotte-Morgan 

> all the content for the standards will be placed in a single mark down document as per the link above

Correct

> graphic elements should be loaded as images or entered as tables

 Correct

> where should images be placed (I'm thinking of the docs work flow here)

There are two options:

1) Commit the images into the docs folder (preferably in a subfolder called images)
2) Drag and drop the image into an empty ticket, copy the resulting markdown link that gets made for the image and paste it into the standards doc, then close the empty ticket without saving.

Option 2 is probably simpler to use.

**Comment by easmetz** [comment]
This looks great - can't wait to get into it! I think this structure will work.

**Comment by timlinux** [comment]
Thanks @easmetz - I'm going to take your comment above as a 'Looks good to me!' and go ahead and merge this so we can get cracking! :-)

**Pull request merged**
