### PR TITLE
Remove multi exposure and metadata converter from the toolbar.

### PR DESCRIPTION
**Pull request by ismailsunni**
### What does it fix?
* Ticket: No ticket
* Funded by: DFAT
* Description: 
   - Remove multi exposure and metadata converter from the toolbar.

### Checklist:
- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [x] Request someone to review or test your PR

### CODE REVIEW

**Comment by Gustry** [comment]
Why not FMT too?
I think this tool is quite specific

**Comment by timlinux** [comment]
Yeah I think we can hide FMT too

**Comment by ismailsunni** [comment]
Thanks, FMT is hiden now.

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux  - can you please remind me the logic as to which tools are on the tool bar and which are  in the menu? Why did we choose to hide the tools here?

**Pull request merged**
