### PR TITLE
fix issue #3934: tidying up infographics:

### PR DESCRIPTION
**Pull request by lucernae**
### What does it fix ?
* Ticket #3934
* Funded by : DFAT

### Description : 
- Don't tag infographic pdf as final product until
  the problem with png generation in composer is resolved
  (html is still working fine)
- Split vulnerabilities into 2 group
- Report displaced number
- Add notes from where displaced number comes from
- Hide slice label if the slice is less than 10%

### CODE REVIEW

**Comment by lucernae** [comment]
Mas @felix-yew I still can't make that triangle in Gender group and Age group 😄 .
I just make a border for now.
I put the from {number} displaced side by side with Vulnerability, since it seems make sense
I modified the displacement notes, since the rate might be different

screen shot 2017-03-03 at 06 05 29

**Comment by timlinux** [comment]
@lucernae there is still a problem here:

inked0764ea70-ffd8-11e6-878e-8f1aaa7fb792_li

**Comment by lucernae** [comment]
@timlinux Can you hand me the icons :smile:

**Comment by felix-yew** [comment]
mas @lucernae I try your PR and the result like this
image
there are only displaced icon? I think in the #3934 we also show the affected and then the displaced in the people section.

> I just make a border for now.
I put the from {number} displaced side by side with Vulnerability, since it seems make sense

LGTM :+1: 


> I modified the displacement notes, since the rate might be different

Can you make like a wrap text and make the font little smaller (if it still can read)


This is the icon for displaced, you can download from this [link](https://thenounproject.com/ochaavmu/collection/ocha-humanitarian-icons/?i=4244)

**Comment by lucernae** [comment]
New preview
screen shot 2017-03-03 at 16 59 36

**Comment by lucernae** [comment]
Using the new icon
screen shot 2017-03-03 at 17 56 43

**Pull request merged**
