### PR TITLE
display extent

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by timlinux** [comment]
Currently QGIS crashes during startup for me with this patch applied to develop. Boring vid:

qgis

**Comment by Gustry** [comment]
This is because it's trying to connect to the pycharm debugger. Sorry for that.
But it's useless to try this PR. It's still **in progress** (the label is there)

**Comment by timlinux** [comment]
Ah sorry I missed the label - thanks...

**Comment by Gustry** [comment]
untitled

**Comment by timlinux** [comment]
@gustry - I just tested this out on my machine - WOW! Awesome stuff - its going to be a big step forward to have this in place.

**Comment by timlinux** [comment]
LGTM

**Pull request merged**
