### PR TITLE
3.2.5 future keyword

### PR DESCRIPTION
**Pull request by ismailsunni**
For fixing #2552 
For more general issue, if inasafe open a layer with invalid xml file.

### CODE REVIEW

**Comment by ismailsunni** [comment]
@samnawi can you try it, please :)

**Comment by ismailsunni** [comment]
Hi @timlinux actually we need to merge this to 3.2.5 first :(

**Comment by samnawi** [comment]
LGTM. I don't get the python error again when to load data with 3.3 keywords.

**Comment by timlinux** [comment]
LGTM

**Comment by timlinux** [comment]
I will make a small bugfix release for 3.2.6 because it may be some days before 3.3 is available.

**Pull request merged**
