### PR TITLE
Realtime bug fix update + merge InaSAFE version 3_5_4

### PR DESCRIPTION
**Pull request by lucernae**
bug fixes will go here until next deployment upgrade, just to store the commits.

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM @lucernae Next time it might be nicer to do the backport merges in one commit and then the fixes in another to make it clearer what is fixes versus merges. It seems like mainly 1dae54d is the fix right? Great to have the layer ordering fixed!

**Comment by timlinux** [comment]
Can you merge this @lucernae so we can keep our PR queue short? Thanks.

**Comment by lucernae** [comment]
@timlinux you mean, I had to create 2 PR? Or I need to squash the backport?

**Comment by lucernae** [comment]
Closing this, will separate it into 2 PR.

**Pull request closed without merging**
