### PR TITLE
debug no keywords

### LINKED ISSUE #4652: Key words missing: set analysis area
## problem ##
When I set the analysis area by selecting an area on the map #4650 and run analysis on a single exposure layer; the resulting impact layer is not printable. The dock shows a message saying the "layer keywords missing:" The print option is greyed out regardless of which element in the output folder I click on.

## proposed solution ##
analysis with selected area on the map canvas should produce results that are printable.

### PR DESCRIPTION
**Pull request by Gustry**
### What does it fix?
* Ticket: #
* Funded by: DFAT
* Description: Try to fix #4652

/!\ Do not merge this PR /!\
Only for testing

@Charlotte-Morgan @ivanbusthomi Can you try to load your layer, run the impact function (or load an existing already) and click on the layer and show what you have in the dock

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
hi @Gustry 
I have tried your pull request. I have the same result with the message "layer keywords missing: in the dock.
image

With this PR I also got a python error
```
2017-11-24T08:46:07	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:07	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
			    self.layer_changed(self.iface.activeLayer())
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:07	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
			    self.layer_changed(self.iface.activeLayer())
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:07	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
			    self.layer_changed(self.iface.activeLayer())
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:08	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
			    self.layer_changed(self.iface.activeLayer())
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:08	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
			    self.layer_changed(self.iface.activeLayer())
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:08	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
			    self.layer_changed(self.iface.activeLayer())
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:14	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:22	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:46:25	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:47:02	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
2017-11-24T08:47:14	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
			    keywords))
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
			    requested_extent)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
			    if not geometry.isGeosValid():
			AttributeError: 'NoneType' object has no attribute 'isGeosValid'
			
```

and the following message in the InaSAFE log
```
2017-11-24T08:45:38	0	Sentry logging enabled in safe
2017-11-24T08:46:02	0	Requested extent : Polygon ((122.1977404000000007 -8.6141173000000002, 122.21643149999999878 -8.6141173000000002, 122.21643149999999878 -8.59312019999999954, 122.1977404000000007 -8.59312019999999954, 122.1977404000000007 -8.6141173000000002))
2017-11-24T08:46:04	0	ANALYSIS : The impact function is starting.
2017-11-24T08:46:04	0	Datastore : C:/temp/TsunamiRasterOnStructuresPolygon_24November2017_08h46-04.670000
2017-11-24T08:46:04	0	ANALYSIS : Pre processing
2017-11-24T08:46:04	0	ANALYSIS : Aggregation preparation
2017-11-24T08:46:04	0	aggregation: provided: False
2017-11-24T08:46:04	0	The aggregation layer is not provided. We are going to create it from the analysis extent and the expected CRS.
2017-11-24T08:46:04	0	impact function: crs: EPSG:4326
2017-11-24T08:46:04	0	aggregation: Convert bbox aggregation to polygon layer with keywords
2017-11-24T08:46:04	0	The exposure is a vector layer. According to the kind of exposure, we need to check if the exposure has some counts before adding some default ratios.
2017-11-24T08:46:04	0	aggregation: Convert the aggregation layer to the analysis layer
2017-11-24T08:46:04	0	ANALYSIS : Hazard preparation
2017-11-24T08:46:04	0	hazard: use_same_projection_as_aggregation: True
2017-11-24T08:46:04	0	hazard: Clip raster by analysis bounding box
2017-11-24T08:46:04	0	hazard: Classify continuous raster hazard
2017-11-24T08:46:04	0	hazard: Polygonize classified raster hazard
2017-11-24T08:46:04	0	hazard: Clip and mask hazard polygons with the analysis layer
2017-11-24T08:46:04	0	hazard: Cleaning the vector hazard attribute table
2017-11-24T08:46:05	0	Features which have been removed from hazard : 0
2017-11-24T08:46:05	0	We add an ID column in hazard
2017-11-24T08:46:05	0	Fields which have been removed from hazard : hazard_val
2017-11-24T08:46:05	0	hazard: Assign classes based on value map
2017-11-24T08:46:05	0	ANALYSIS : Aggregate hazard preparation
2017-11-24T08:46:05	0	hazard: Make hazard layer valid
2017-11-24T08:46:05	0	aggregation: Union hazard polygons with aggregation areas and assign hazard class
2017-11-24T08:46:05	0	ANALYSIS : Exposure preparation
2017-11-24T08:46:05	0	exposure: use_same_projection_as_aggregation: True
2017-11-24T08:46:05	0	exposure: Smart clip
2017-11-24T08:46:05	0	exposure: Cleaning the vector exposure attribute table
2017-11-24T08:46:05	0	Features which have been removed from exposure : 0
2017-11-24T08:46:05	0	We add an ID column in exposure
2017-11-24T08:46:05	0	Fields which have been removed from exposure : BUILDING STRUCTURE WALL_TYPE ROOF_TYPE LEVELS ADMIN ROOF_ACCES CAPACITY RELIGION OSM_TYPE FULL_ADDRE NAME AMENITY LEISURE USE OFFICE TYPE
2017-11-24T08:46:05	0	exposure: Compute ratios from counts
2017-11-24T08:46:05	0	Population count field population_count_field is not detected in the exposure. We will not compute a ratio from this field because the formula needs Population count field. Formula: ratio = subset count / total count.
2017-11-24T08:46:05	0	exposure: Add default values
2017-11-24T08:46:05	0	inasafe_default_value is not present, we can not fill default ratios for this layer.
2017-11-24T08:46:05	0	exposure: Assign classes based on value map
2017-11-24T08:46:05	0	ANALYSIS : Intersect Exposure and Aggregate Hazard
2017-11-24T08:46:05	0	impact function: Highest class of hazard is assigned to the exposure
2017-11-24T08:46:05	0	ANALYSIS : Post processing
2017-11-24T08:46:05	0	The size calculator is set to use Meters
2017-11-24T08:46:05	0	post_processor: Size Value Post Processor
2017-11-24T08:46:05	0	Size Value Post Processor : Running
2017-11-24T08:46:05	0	post_processor: Affected Post Processor
2017-11-24T08:46:05	0	Affected Post Processor : Running
2017-11-24T08:46:05	0	ANALYSIS : Summary calculation
2017-11-24T08:46:05	0	impact function: Aggregate the impact summary
2017-11-24T08:46:05	0	Computing the aggregate hazard summary.
2017-11-24T08:46:05	0	impact function: Aggregate the aggregation summary
2017-11-24T08:46:05	0	impact function: Aggregate the analysis summary
2017-11-24T08:46:05	0	impact function: Build the exposure summary table
2017-11-24T08:46:06	0	Layer saved impact_analysis
2017-11-24T08:46:06	0	Layer saved hazard_aggregation_summary
2017-11-24T08:46:06	0	Layer saved exposure_summary_table
2017-11-24T08:46:06	0	Layer saved aggregation_summary
2017-11-24T08:46:06	0	Layer saved analysis_summary
2017-11-24T08:46:06	0	Layer saved Analysis Log
2017-11-24T08:46:06	0	ANALYSIS : Styling
2017-11-24T08:46:06	0	Aggregation None
2017-11-24T08:46:06	0	The impact function could run without errors.
2017-11-24T08:46:07	0	Showing No Keywords Message
2017-11-24T08:46:07	0	Showing No Keywords Message
2017-11-24T08:46:07	0	Showing No Keywords Message
2017-11-24T08:46:07	0	Showing No Keywords Message
2017-11-24T08:46:07	0	InaSAFE Impact Report class initialised
2017-11-24T08:46:08	0	Showing No Keywords Message
2017-11-24T08:46:08	0	Showing No Keywords Message
2017-11-24T08:46:08	0	Showing No Keywords Message
2017-11-24T08:46:14	0	Showing No Keywords Message
2017-11-24T08:46:22	0	Showing No Keywords Message
2017-11-24T08:46:25	0	Showing No Keywords Message
2017-11-24T08:47:02	0	Showing No Keywords Message
2017-11-24T08:47:14	0	Showing No Keywords Message
```
My interpretation is that the bounding box is not being recognised as an aggregation area.

**Comment by Gustry** [comment]
@myarjunar So this PR helps you to fix the error?

I think I will try to remove the `AttributeError`, @ismailsunni any memory why this exception? It was hidding us a real error in the code

**Comment by myarjunar** [comment]
@Gustry yes, I know where is the error because of the traceback, tahnks

**Comment by ismailsunni** [comment]
I am sorry, I can't remember anything about this.

**Pull request closed without merging**
