### PR TITLE
polygonize volcanos point, use QGIS api in buffering

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by Gustry** [comment]
Scrutinizer is failing, I don't know why and I can't reload it. Travis is OK.
But this PR is ready to be merged. It removes the geodesy module, and polygonize volcanos in the `prepare` function.

CC : @timlinux @ismailsunni @lucernae

**Comment by ismailsunni** [comment]
May be, for now, we can disable scrutinizer first until we have a good configuration for it.

**Comment by timlinux** [comment]
Can you please add tests for ``def buffer_points(point_layer, radii, hazard_zone_attribute, output_crs):`` with a few test cases for different projection.

Once we have that, LGTM to merge thanks.

**Comment by Gustry** [comment]
Hi @timlinux I added some unit test and I changed some functions.
I added a new test function to compare two layers. Is-it possible to review again ? Thanks

**Comment by timlinux** [comment]
LGTM thanks @Gustry

**Pull request merged**
