### PR TITLE
Fix 2612 and 2610

### PR DESCRIPTION
**Pull request by ismailsunni**
For #2612 and #2610

### CODE REVIEW

**Comment by ismailsunni** [comment]
Sample result of the new legend:
screen shot 2016-02-05 at 3 02 00 pm

**Comment by samnawi** [comment]
LGTM

**Comment by Charlotte-Morgan** [comment]
thanks @ismailsunni - this looks better, normally we use mutually exclusive values but I will wait for someone else to ask for that :)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
Yes, my math-sense also thinks they should be mutually exclusive. In the calculation, they are indeed mutually exclusive. So, I prefer something like this:

Dry Zone : depth = 0 m
Low Hazard Zone : 0 < depth <= 1.0
Medium Hazard Zone : 1.0 < depth <= 3.0
High Hazard Zone : 3.0 < depth <= 8.0
Very High Hazard Zone : 8.0 < depth

**Comment by Charlotte-Morgan** [comment]
have a look at #2612 - I give specific values in that.
Or in your example above; IIRC, the bottom of the range is normally greater than the top of the previous range.

so if low goes up to 1.0
medium will be greater than 1.0 up to 3.0
high will be greater than 3.0 up to 8.0 
etc

**Comment by ismailsunni** [comment]
In the example #2612, there is no legend for 0.05. So, it doesn't cover all values.

Do we need to update the legend now?

**Comment by Charlotte-Morgan** [comment]
i think you need to tweak it as per my comment above

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
Sorry, I think I miss-understood your comment. So, I made another one:
screen shot 2016-02-09 at 8 37 30 am
see my PR on #2622

**Pull request merged**
