### PR TITLE
Updates to SPHERE standards - see #3065

### PR DESCRIPTION
**Pull request by timlinux**

### CODE REVIEW

**Comment by timlinux** [comment]
screen shot 2016-08-01 at 9 02 53 am

@fredychandra FYI above is a screenshot of how SPHERE outputs currently look...

**Comment by timlinux** [comment]
Here is what the output currently looks like @fredychandra 

screen shot 2016-08-01 at 9 13 49 am

**Comment by fredychandra** [comment]
Hi @timlinux 

Can you please add the item list below to complete sphere minimum standard default ?
- Soap : 250 gram/person/month
- Detergent : 200 gram/person/month
- Stove : 1 pc/HH (5 persons

Thanks

**Comment by timlinux** [comment]
Hi @fredychandra 

I updated according to your requests:

screen shot 2016-08-04 at 1 48 42 pm

**Comment by timlinux** [comment]
@fredychandra can we go ahead and merge this?

**Comment by timlinux** [comment]
@fredychandra I'm going to merge this - we can tweak it in a follow up ticket if needed ok?

**Comment by fredychandra** [comment]
Hi @timlinux  sorry just replied. I am at Ambon now for Ambon TTX preparation.  Yes we can follow up ticket if needed. tx

**Comment by timlinux** [comment]
Ok perfect thanks @fredychandra

**Pull request merged**
