### PR TITLE
Standardise style version in all qmls

### PR DESCRIPTION
**Pull request by timlinux**
Also updates changelog. Don't merge yet

### CODE REVIEW

**Comment by timlinux** [comment]
@ismailsunni can you review - I basically updated all QML's so we get rid of all those nasty messages clogging up the stdout (about outdated styles).

**Comment by ismailsunni** [comment]
Ah, shorter stdout.... Now, I can see some message, e.g. https://travis-ci.org/inasafe/inasafe/builds/105497288#L1693.

And of course, LGTM.

Related issue : #2594

**Comment by timlinux** [comment]
For the record the impetus behind this PR is that the QML version causes lots of debug messages in QGIS if it is older than the current version - so much so that our tests exceed the 10000 line maximum for travis logs and it is basically impossible to see useful information between all the log 'spam'. Here is the before example:

selection_002

And here are two pics with my changes applied:

selection_001


selection_003

**Comment by timlinux** [comment]
I also fixed it upstream in QGIS: https://github.com/qgis/QGIS/commit/e15c7fb96cf25e3f716b28eebd48a9719642c2a4

https://github.com/qgis/QGIS/pull/2734

**Pull request merged**
