### PR TITLE
Minor text tweaks

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
added single and multi event notes for volcano - experiment for #3098 
other minor text tweaks

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - grateful if you can explain my error

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - can you explain what is wrong with this file? Why Travis is not happy?

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan 
The reason is because you changed the strings, and those strings that you replaced are expected in the test.

A gist from the travis:
```
(impact_functions.generic.classified_polygon_landcover.test.test_classified_polygon_landcover.TestClassifiedPolygonLandCoverFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests_directory/safe/impact_functions/generic/classified_polygon_landcover/test/test_classified_polygon_landcover.py", line 80, in test_run
    function.notes())
AssertionError: u'Areas reported for land cover counts have not been rounded.' not found in [u'The classes used for low, medium, high hazard are specific to the hazard dataset used.', u'Please consult the original hazard dataset creator for more details.', u'Areas reported for land cover have not been rounded.']
```

And looking at your changes here : https://github.com/inasafe/inasafe/pull/3100/files#diff-65559d462c2042253a1ddf38c89b3efaL520

You have replaced _Areas reported for land cover counts have not been rounded._ with _Areas reported for land cover have not been rounded._

You can fix this by editing this file : safe/impact_functions/generic/classified_polygon_landcover/test/test_classified_polygon_landcover.py on line 80, and do the same update for the string there.

**Comment by Charlotte-Morgan** [comment]
wah - we have text strings in tests ?

**Comment by ismailsunni** [comment]
@Charlotte-Morgan yes, more test is better. :)
We do it to check whether the report is correct or not, since sometimes we change text and the report changes but we do not aware.

**Comment by Charlotte-Morgan** [comment]
thank you

**Comment by ismailsunni** [comment]
LGTM @Charlotte-Morgan 👍

**Pull request merged**
