### PR TITLE
Another print dialog polish

### PR DESCRIPTION
**Pull request by myarjunar**
### What does it fix?
* Ticket: #4803 #4795 
* Funded by: DFAT
* Description: 
impact report_168

impact report_172

### Checklist:
- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Add to the changelog in metadata.txt if it's a new feature
- [ ] Unit test for new code added
- [ ] Request someone to review or test your PR

### CODE REVIEW

**Comment by timlinux** [comment]
Can you share how it looks currently?

**Comment by Gustry** [comment]
Can you change to `Print the map as PDF`?
According to my comments here https://github.com/inasafe/inasafe/pull/4779#issuecomment-351354602 when we put use `Print` without the `as PDF`

**Comment by myarjunar** [comment]
@Gustry do you mean change the `Open as PDF` button to `Print the map as PDF`?

**Comment by Gustry** [comment]
`Print the map using`.

I would also remove `InaSAFE report`, maybe only `Reports`, because we are already in InaSAFE, so it looks redundant.

**Comment by myarjunar** [comment]
@Gustry ah ok, I'm just following what's in #4803 and there is still no other feedback, personally I prefer what's @Charlotte-Morgan proposing in #4803

**Comment by Gustry** [comment]
Ah yes ok.
Will you just update the `as PDF` ?

**Comment by timlinux** [comment]
One other thing we discussed @myarjunar was that the old text should be moved into the help dialog strings. Can you do this please? Add a paragraph for each checkbox / option in the dialog with the current (as per your screenshot above) text and then a : then the old detailed explanation.

Also please check that that help text goes into the definitions_help (it needs a couple of lines to add it into the list of help texts for dialogs).

Thanks.

**Pull request merged**
