### PR TITLE
Add logo for place and image credit #3405.

### PR DESCRIPTION
**Pull request by ismailsunni**
- Add logo for place #3045 
- Add image credit

### CODE REVIEW

**Comment by timlinux** [comment]
Great thanks. Can you confirm via a screenshot that is shows up in the wizard? If so LGTM

**Comment by ismailsunni** [comment]
Hi @timlinux This is the screenshot:
screen shot 2016-08-10 at 17 32 09

**Comment by lucernae** [comment]
LGTM

**Comment by timlinux** [comment]
Thanks @ismailsunni - it shows on the IFCW too? Then LGTM

**Comment by ismailsunni** [comment]
@timlinux yes, it does:
screen shot 2016-08-10 at 18 07 43

**Pull request merged**
