### PR TITLE
Added webhook for travis to inasafe-notices matrix room

### PR DESCRIPTION
**Pull request by timlinux**
### What does it fix ?
* Ticket #
* Funded by : Tim
* Description :  Added a web hook for travis to matrix

### CODE REVIEW

**Comment by timlinux** [comment]
@Gustry hmm not its not wanted

**Comment by ismailsunni** [comment]
@timlinux just reset --soft your PR, and checkout the safe_extras parameter.

**Comment by timlinux** [comment]
hmm still does not fix it @ismailsunni

**Comment by ismailsunni** [comment]
Ah sorry, it should be like this:
1. git reset --soft HEAD^
2. git reset HEAD safe_extras/parameters/
3. git submodule update

If you don't mind, I have made a fix here https://github.com/inasafe/inasafe/pull/4081

**Pull request closed without merging**
